/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_SHA3512_i64o64_spongeFSM
    ( // Inputs
      input wire logic c$ds_bindCsr  // clock
    , input wire logic c$ds_bindCsr_0  // reset
    , input wire logic c$ds_bindCsr_1  // enable
    , input wire dut_types::Tuple3_0 eta1

      // Outputs
    , output dut_types::Tuple2_4 result
    );
  logic [63:0] result_0;
  logic [63:0] c$case_alt;
  logic [63:0] c$case_alt_0;
  logic [63:0] c$case_alt_1;
  logic [63:0] c$case_alt_2;
  logic [63:0] c$case_alt_3;
  logic [63:0] c$case_alt_4;
  logic [63:0] c$case_alt_5;
  logic [1599:0] c$app_arg;
  logic [1599:0] state;
  dut_types::State i64o64Core_ds1 = {{2'b00,4'd0,3'bxxx}
,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
  dut_types::Tuple2 c$ds_case_alt;
  dut_types::Tuple2 result_1;
  dut_types::State c$ds_app_arg;
  dut_types::State c$ds_app_arg_0;
  logic [2:0] counter;
  dut_types::Tuple2 c$ds_case_alt_0;
  logic tready;
  logic [1:0] seenTLAST;
  logic [4:0] counter_0;
  dut_types::Tuple2 result_2;
  dut_types::Tuple2 c$case_alt_6;
  dut_types::Tuple2 c$case_alt_7;
  dut_types::Tuple2 result_3;
  dut_types::Tuple2 c$case_alt_8;
  logic c$app_arg_0;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_5;
  logic signed [63:0] c$app_arg_2;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_6;
  logic signed [63:0] c$app_arg_4;
  logic [1599:0] c$app_arg_5;
  logic [10:0] c$complementAt1_arg0;
  logic [10:0] c$complementAt1_arg0_case_alt;
  logic [10:0] c$complementAt1_arg0_case_alt_0;
  logic [10:0] c$complementAt1_arg0_case_alt_1;
  logic [10:0] c$complementAt1_arg0_case_alt_2;
  logic [10:0] c$complementAt1_arg0_case_alt_3;
  logic [10:0] c$complementAt1_arg0_case_alt_4;
  logic [10:0] c$complementAt1_arg0_case_alt_5;
  logic [10:0] c$complementAt1_arg0_case_alt_6;
  dut_types::Tuple2_3 c$complementAt1_tupIn;
  logic c$complementAt1_tupIn_case_scrut;
  dut_types::Tuple2_3 result_7;
  dut_types::Tuple2_3 c$complementAt1_tupIn_case_alt;
  dut_types::Tuple2_3 c$complementAt1_tupIn_case_alt_0;
  dut_types::Tuple2_3 c$complementAt1_tupIn_case_alt_1;
  dut_types::Tuple2_3 c$complementAt1_tupIn_case_alt_2;
  dut_types::Tuple2_3 c$complementAt1_tupIn_case_alt_3;
  dut_types::Tuple2_3 c$complementAt1_tupIn_case_alt_4;
  dut_types::Tuple2_3 c$complementAt1_tupIn_case_alt_5;
  logic [1599:0] result_8;
  logic [1599:0] c$case_alt_9;
  logic [1599:0] c$case_alt_10;
  logic [1599:0] c$case_alt_11;
  logic [1599:0] c$case_alt_12;
  logic [1599:0] c$case_alt_13;
  logic [1599:0] c$case_alt_14;
  logic [1599:0] c$case_alt_15;
  logic [1599:0] c$case_alt_16;
  logic [1599:0] c$case_alt_17;
  logic [1599:0] c$case_alt_18;
  logic [1599:0] c$case_alt_19;
  logic [1599:0] c$case_alt_20;
  logic [1599:0] c$case_alt_21;
  logic [1599:0] c$case_alt_22;
  logic [1599:0] c$case_alt_23;
  logic [1599:0] c$case_alt_24;
  logic [1599:0] c$case_alt_25;
  logic [1599:0] c$app_arg_6;
  logic c$complementAt1_tupIn_case_scrut_0;
  logic c$complementAt1_tupIn_case_scrut_1;
  logic c$complementAt1_tupIn_case_scrut_2;
  logic c$complementAt1_tupIn_case_scrut_3;
  logic c$complementAt1_tupIn_case_scrut_4;
  logic c$complementAt1_tupIn_case_scrut_5;
  logic c$complementAt1_tupIn_case_scrut_6;
  logic c$complementAt1_tupIn_case_scrut_7;
  logic flush;
  dut_types::AXI4Stream \input ;
  logic [3:0] counter_1;
  logic [8:0] c$ds_case_alt_selection_1;
  logic [10:0] c$i_28;

  assign result = c$ds_case_alt.Tuple2_sel1;

  assign result_0 = (counter == 3'd0) ? (c$app_arg[63 : 0]) : c$case_alt;

  assign c$case_alt = (counter == 3'd1) ? (c$app_arg[127 : 64]) : c$case_alt_0;

  assign c$case_alt_0 = (counter == 3'd2) ? (c$app_arg[191 : 128]) : c$case_alt_1;

  assign c$case_alt_1 = (counter == 3'd3) ? (c$app_arg[255 : 192]) : c$case_alt_2;

  assign c$case_alt_2 = (counter == 3'd4) ? (c$app_arg[319 : 256]) : c$case_alt_3;

  assign c$case_alt_3 = (counter == 3'd5) ? (c$app_arg[383 : 320]) : c$case_alt_4;

  assign c$case_alt_4 = (counter == 3'd6) ? (c$app_arg[447 : 384]) : c$case_alt_5;

  assign c$case_alt_5 = (counter == 3'd7) ? (c$app_arg[511 : 448]) : ({64 {1'bx}});

  assign c$app_arg = state;

  assign state = i64o64Core_ds1.State_sel1;

  // register begin
  always_ff @(posedge c$ds_bindCsr or  posedge  c$ds_bindCsr_0) begin : i64o64Core_ds1_register
    if ( c$ds_bindCsr_0) begin
      i64o64Core_ds1 <= {{2'b00,4'd0,3'bxxx}
  ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
    end else  if (c$ds_bindCsr_1)  begin
      i64o64Core_ds1 <= c$ds_case_alt.Tuple2_sel0;
    end
  end
  // register end

  assign c$ds_case_alt_selection_1 = i64o64Core_ds1.State_sel0;

  always_comb begin
    case(c$ds_case_alt_selection_1[8:7])
      2'b00 : c$ds_case_alt = result_2;
      2'b01 : c$ds_case_alt = c$ds_case_alt_0;
      default : c$ds_case_alt = result_1;
    endcase
  end

  assign result_1 = (counter == 3'd7) ? {c$ds_app_arg
                                        ,{{result_0,1'b1,1'b1},1'b0}} : {c$ds_app_arg_0
                                                                        ,{{result_0,1'b1,1'b0},1'b0}};

  assign c$ds_app_arg = tready ? {{2'b00,4'd0,3'bxxx}
                                 ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000} : {{2'b10,3'd7,4'bxxxx}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ,state};

  assign c$ds_app_arg_0 = tready ? {{2'b10,counter + 3'd1,4'bxxxx}
                                   ,state} : i64o64Core_ds1;

  assign counter = i64o64Core_ds1[1606:1604];

  Component_SHA3512_i64o64_pad i64o64Core_Component_SHA3512_i64o64_pad_c$ds_case_alt_0
    ( .result (c$ds_case_alt_0)
    , .eta2 (counter_0)
    , .eta3 (seenTLAST)
    , .eta4 (state)
    , .eta5 (tready) );

  assign tready = eta1.Tuple3_0_sel1;

  assign seenTLAST = i64o64Core_ds1[1601:1600];

  assign counter_0 = i64o64Core_ds1[1606:1602];

  assign result_2 = c$complementAt1_tupIn_case_scrut ? {{{2'b01,5'd0,2'd0}
                                                        ,result_4}
                                                       ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                         ,1'b0
                                                         ,1'b0}
                                                        ,1'b0}} : c$case_alt_6;

  assign c$case_alt_6 = (~ \input .AXI4Stream_sel1) ? {{{2'b00,counter_1,3'bxxx}
                                                       ,state}
                                                      ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                        ,1'b0
                                                        ,1'b0}
                                                       ,1'b1}} : c$case_alt_7;

  assign c$case_alt_7 = (\input .AXI4Stream_sel2 & c$app_arg_0) ? {{{2'b01,5'd0,2'd0}
                                                                   ,result_4}
                                                                  ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                                    ,1'b0
                                                                    ,1'b0}
                                                                   ,1'b0}} : result_3;

  assign result_3 = \input .AXI4Stream_sel2 ? {{{2'b01,5'd0,2'd1}
                                               ,result_8}
                                              ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                ,1'b0
                                                ,1'b0}
                                               ,1'b0}} : c$case_alt_8;

  assign c$case_alt_8 = c$app_arg_0 ? {{{2'b00,counter_1 + 4'd1,3'bxxx}
                                       ,result_8}
                                      ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                        ,1'b0
                                        ,1'b0}
                                       ,1'b1}} : {{{2'b01,5'd0,2'd2},result_8}
                                                 ,{{64'b0000000000000000000000000000000000000000000000000000000000000000
                                                   ,1'b0
                                                   ,1'b0}
                                                  ,1'b0}};

  assign c$app_arg_0 = counter_1 < 4'd8;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_1;
    result_4[64'sd575] = (~ (c$app_arg_1[64'sd575]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_3;
    result_5[c$app_arg_2] = (~ (c$app_arg_3[c$app_arg_2]));
  end
  // replaceBit end

  assign c$app_arg_2 = $unsigned({{(64-11) {1'b0}},c$complementAt1_arg0});

  assign c$app_arg_3 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_5;
    result_6[c$app_arg_4] = (~ (c$app_arg_5[c$app_arg_4]));
  end
  // replaceBit end

  assign c$i_28 = c$complementAt1_tupIn.Tuple2_3_sel0;

  assign c$app_arg_4 = $unsigned({{(64-11) {1'b0}},c$i_28});

  assign c$app_arg_5 = c$complementAt1_tupIn.Tuple2_3_sel1;

  assign c$complementAt1_arg0 = c$complementAt1_tupIn_case_scrut ? 11'd2 : c$complementAt1_arg0_case_alt;

  assign c$complementAt1_arg0_case_alt = c$complementAt1_tupIn_case_scrut_7 ? 11'd66 : c$complementAt1_arg0_case_alt_0;

  assign c$complementAt1_arg0_case_alt_0 = c$complementAt1_tupIn_case_scrut_6 ? 11'd130 : c$complementAt1_arg0_case_alt_1;

  assign c$complementAt1_arg0_case_alt_1 = c$complementAt1_tupIn_case_scrut_5 ? 11'd194 : c$complementAt1_arg0_case_alt_2;

  assign c$complementAt1_arg0_case_alt_2 = c$complementAt1_tupIn_case_scrut_4 ? 11'd258 : c$complementAt1_arg0_case_alt_3;

  assign c$complementAt1_arg0_case_alt_3 = c$complementAt1_tupIn_case_scrut_3 ? 11'd322 : c$complementAt1_arg0_case_alt_4;

  assign c$complementAt1_arg0_case_alt_4 = c$complementAt1_tupIn_case_scrut_2 ? 11'd386 : c$complementAt1_arg0_case_alt_5;

  assign c$complementAt1_arg0_case_alt_5 = c$complementAt1_tupIn_case_scrut_1 ? 11'd450 : c$complementAt1_arg0_case_alt_6;

  assign c$complementAt1_arg0_case_alt_6 = c$complementAt1_tupIn_case_scrut_0 ? 11'd514 : 11'd2;

  assign c$complementAt1_tupIn = c$complementAt1_tupIn_case_scrut ? {11'd1
                                                                    ,state} : result_7;

  assign c$complementAt1_tupIn_case_scrut = flush & (counter_1 == 4'd0);

  assign result_7 = c$complementAt1_tupIn_case_scrut_7 ? {11'd65
                                                         ,result_8} : c$complementAt1_tupIn_case_alt;

  assign c$complementAt1_tupIn_case_alt = c$complementAt1_tupIn_case_scrut_6 ? {11'd129
                                                                               ,result_8} : c$complementAt1_tupIn_case_alt_0;

  assign c$complementAt1_tupIn_case_alt_0 = c$complementAt1_tupIn_case_scrut_5 ? {11'd193
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_1;

  assign c$complementAt1_tupIn_case_alt_1 = c$complementAt1_tupIn_case_scrut_4 ? {11'd257
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_2;

  assign c$complementAt1_tupIn_case_alt_2 = c$complementAt1_tupIn_case_scrut_3 ? {11'd321
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_3;

  assign c$complementAt1_tupIn_case_alt_3 = c$complementAt1_tupIn_case_scrut_2 ? {11'd385
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_4;

  assign c$complementAt1_tupIn_case_alt_4 = c$complementAt1_tupIn_case_scrut_1 ? {11'd449
                                                                                 ,result_8} : c$complementAt1_tupIn_case_alt_5;

  assign c$complementAt1_tupIn_case_alt_5 = c$complementAt1_tupIn_case_scrut_0 ? {11'd513
                                                                                 ,result_8} : {11'd1,result_8};

  assign result_8 = (counter_1 == 4'd0) ? c$case_alt_9 : c$case_alt_10;

  // setSlice begin
  always_comb begin
    c$case_alt_9 = c$app_arg_6;
    c$case_alt_9[63 : 0] = ((c$app_arg_6[63 : 0]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_10 = (counter_1 == 4'd1) ? c$case_alt_11 : c$case_alt_12;

  // setSlice begin
  always_comb begin
    c$case_alt_11 = c$app_arg_6;
    c$case_alt_11[127 : 64] = ((c$app_arg_6[127 : 64]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_12 = (counter_1 == 4'd2) ? c$case_alt_13 : c$case_alt_14;

  // setSlice begin
  always_comb begin
    c$case_alt_13 = c$app_arg_6;
    c$case_alt_13[191 : 128] = ((c$app_arg_6[191 : 128]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_14 = (counter_1 == 4'd3) ? c$case_alt_15 : c$case_alt_16;

  // setSlice begin
  always_comb begin
    c$case_alt_15 = c$app_arg_6;
    c$case_alt_15[255 : 192] = ((c$app_arg_6[255 : 192]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_16 = (counter_1 == 4'd4) ? c$case_alt_17 : c$case_alt_18;

  // setSlice begin
  always_comb begin
    c$case_alt_17 = c$app_arg_6;
    c$case_alt_17[319 : 256] = ((c$app_arg_6[319 : 256]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_18 = (counter_1 == 4'd5) ? c$case_alt_19 : c$case_alt_20;

  // setSlice begin
  always_comb begin
    c$case_alt_19 = c$app_arg_6;
    c$case_alt_19[383 : 320] = ((c$app_arg_6[383 : 320]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_20 = (counter_1 == 4'd6) ? c$case_alt_21 : c$case_alt_22;

  // setSlice begin
  always_comb begin
    c$case_alt_21 = c$app_arg_6;
    c$case_alt_21[447 : 384] = ((c$app_arg_6[447 : 384]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_22 = (counter_1 == 4'd7) ? c$case_alt_23 : c$case_alt_24;

  // setSlice begin
  always_comb begin
    c$case_alt_23 = c$app_arg_6;
    c$case_alt_23[511 : 448] = ((c$app_arg_6[511 : 448]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$case_alt_24 = (counter_1 == 4'd8) ? c$case_alt_25 : state;

  // setSlice begin
  always_comb begin
    c$case_alt_25 = c$app_arg_6;
    c$case_alt_25[575 : 512] = ((c$app_arg_6[575 : 512]) ^ \input .AXI4Stream_sel0);
  end
  // setSlice end

  assign c$app_arg_6 = state;

  assign c$complementAt1_tupIn_case_scrut_0 = counter_1 == 4'd7;

  assign c$complementAt1_tupIn_case_scrut_1 = counter_1 == 4'd6;

  assign c$complementAt1_tupIn_case_scrut_2 = counter_1 == 4'd5;

  assign c$complementAt1_tupIn_case_scrut_3 = counter_1 == 4'd4;

  assign c$complementAt1_tupIn_case_scrut_4 = counter_1 == 4'd3;

  assign c$complementAt1_tupIn_case_scrut_5 = counter_1 == 4'd2;

  assign c$complementAt1_tupIn_case_scrut_6 = counter_1 == 4'd1;

  assign c$complementAt1_tupIn_case_scrut_7 = counter_1 == 4'd0;

  assign flush = eta1.Tuple3_0_sel2;

  assign \input  = eta1.Tuple3_0_sel0;

  assign counter_1 = i64o64Core_ds1[1606:1603];


endmodule

