/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module dut
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [271:0] MSG_TDATA
    , input wire logic MSG_TVALID
    , input wire logic MSG_TLAST
    , input wire logic XOF_TREADY

      // Outputs
    , output logic [47:0] XOF_TDATA
    , output logic XOF_TVALID
    , output logic XOF_TLAST
    , output logic MSG_TREADY
    );
  dut_types::State c$ds_app_arg = {{2'b00,5'bxxxxx}
,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
  dut_types::Tuple2_2 result_0;
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] result_1;
  logic [1599:0] c$app_arg;
  logic [1599:0] result_2;
  logic [1599:0] c$app_arg_0;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_4;
  dut_types::Tuple2_3 result_7;
  dut_types::State c$case_alt;
  dut_types::State c$app_arg_5;
  logic [47:0] result_8;
  logic [47:0] c$case_alt_0;
  logic [47:0] c$case_alt_1;
  logic [47:0] c$case_alt_2;
  logic [47:0] c$case_alt_3;
  logic [47:0] c$case_alt_4;
  logic [47:0] c$case_alt_5;
  logic [47:0] c$case_alt_6;
  logic [47:0] c$case_alt_7;
  logic [47:0] c$case_alt_8;
  logic [47:0] c$case_alt_9;
  logic [47:0] c$case_alt_10;
  logic [47:0] c$case_alt_11;
  logic [47:0] c$case_alt_12;
  logic [47:0] c$case_alt_13;
  logic [47:0] c$case_alt_14;
  logic [47:0] c$case_alt_15;
  logic [47:0] c$case_alt_16;
  logic [47:0] c$case_alt_17;
  logic [47:0] c$case_alt_18;
  logic [47:0] c$case_alt_19;
  logic [47:0] c$case_alt_20;
  logic [47:0] c$case_alt_21;
  logic [47:0] c$case_alt_22;
  logic [47:0] c$case_alt_23;
  logic [47:0] c$case_alt_24;
  logic [47:0] c$case_alt_25;
  logic [47:0] c$case_alt_26;
  logic [1599:0] c$app_arg_6;
  dut_types::Tuple2_3 c$case_alt_27;
  dut_types::Tuple2_3 c$case_alt_28;
  logic [6:0] phase;
  logic [1599:0] state;
  logic tready;
  logic [271:0] inputMsg;
  logic msgValid;
  logic [4:0] counter;
  logic [4:0] counter_0;
  dut_types::Tuple2_4 c$arg;
  dut_types::Tuple2_5 result;
  dut_types::AXI4Stream XOF;

  assign c$arg = {{MSG_TDATA
                  ,MSG_TVALID
                  ,MSG_TLAST}
                 ,XOF_TREADY};

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {{2'b00,5'bxxxxx}
  ,1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt_28.Tuple2_3_sel0;
    end
  end
  // register end

  assign result_0 = c$case_alt_28.Tuple2_3_sel1;

  Component_XOF_i272o48_keccakF1600 Component_XOF_i272o48_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (counter)
    , .x (state) );

  // replaceBit start
  always_comb begin
    result_1 = c$app_arg;
    result_1[64'sd276] = (~ (c$app_arg[64'sd276]));
  end
  // replaceBit end

  assign c$app_arg = ({1328'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,inputMsg});

  // replaceBit start
  always_comb begin
    result_2 = c$app_arg_0;
    result_2[64'sd275] = (~ (c$app_arg_0[64'sd275]));
  end
  // replaceBit end

  assign c$app_arg_0 = result_1;

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_1;
    result_3[64'sd274] = (~ (c$app_arg_1[64'sd274]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_2;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_2;
    result_4[64'sd273] = (~ (c$app_arg_2[64'sd273]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_3;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_3;
    result_5[64'sd272] = (~ (c$app_arg_3[64'sd272]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_4;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_4;
    result_6[64'sd1343] = (~ (c$app_arg_4[64'sd1343]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_5;

  assign result_7 = (counter == 5'd23) ? {{{2'b10,5'd0}
                                          ,c$keccakF1600_out}
                                         ,{1'b0
                                          ,{48'b000000000000000000000000000000000000000000000000
                                           ,1'b0
                                           ,1'b0}}} : {{{2'b01,counter + 5'd1}
                                                       ,c$keccakF1600_out}
                                                      ,{1'b0
                                                       ,{48'b000000000000000000000000000000000000000000000000
                                                        ,1'b0
                                                        ,1'b0}}};

  assign c$case_alt = (counter_0 == 5'd27) ? {{2'b01,5'd0}
                                             ,state} : {{2'b10,counter_0 + 5'd1},state};

  assign c$app_arg_5 = tready ? c$case_alt : c$ds_app_arg;

  assign result_8 = (counter_0 == 5'd0) ? (c$app_arg_6[47 : 0]) : c$case_alt_0;

  assign c$case_alt_0 = (counter_0 == 5'd1) ? (c$app_arg_6[95 : 48]) : c$case_alt_1;

  assign c$case_alt_1 = (counter_0 == 5'd2) ? (c$app_arg_6[143 : 96]) : c$case_alt_2;

  assign c$case_alt_2 = (counter_0 == 5'd3) ? (c$app_arg_6[191 : 144]) : c$case_alt_3;

  assign c$case_alt_3 = (counter_0 == 5'd4) ? (c$app_arg_6[239 : 192]) : c$case_alt_4;

  assign c$case_alt_4 = (counter_0 == 5'd5) ? (c$app_arg_6[287 : 240]) : c$case_alt_5;

  assign c$case_alt_5 = (counter_0 == 5'd6) ? (c$app_arg_6[335 : 288]) : c$case_alt_6;

  assign c$case_alt_6 = (counter_0 == 5'd7) ? (c$app_arg_6[383 : 336]) : c$case_alt_7;

  assign c$case_alt_7 = (counter_0 == 5'd8) ? (c$app_arg_6[431 : 384]) : c$case_alt_8;

  assign c$case_alt_8 = (counter_0 == 5'd9) ? (c$app_arg_6[479 : 432]) : c$case_alt_9;

  assign c$case_alt_9 = (counter_0 == 5'd10) ? (c$app_arg_6[527 : 480]) : c$case_alt_10;

  assign c$case_alt_10 = (counter_0 == 5'd11) ? (c$app_arg_6[575 : 528]) : c$case_alt_11;

  assign c$case_alt_11 = (counter_0 == 5'd12) ? (c$app_arg_6[623 : 576]) : c$case_alt_12;

  assign c$case_alt_12 = (counter_0 == 5'd13) ? (c$app_arg_6[671 : 624]) : c$case_alt_13;

  assign c$case_alt_13 = (counter_0 == 5'd14) ? (c$app_arg_6[719 : 672]) : c$case_alt_14;

  assign c$case_alt_14 = (counter_0 == 5'd15) ? (c$app_arg_6[767 : 720]) : c$case_alt_15;

  assign c$case_alt_15 = (counter_0 == 5'd16) ? (c$app_arg_6[815 : 768]) : c$case_alt_16;

  assign c$case_alt_16 = (counter_0 == 5'd17) ? (c$app_arg_6[863 : 816]) : c$case_alt_17;

  assign c$case_alt_17 = (counter_0 == 5'd18) ? (c$app_arg_6[911 : 864]) : c$case_alt_18;

  assign c$case_alt_18 = (counter_0 == 5'd19) ? (c$app_arg_6[959 : 912]) : c$case_alt_19;

  assign c$case_alt_19 = (counter_0 == 5'd20) ? (c$app_arg_6[1007 : 960]) : c$case_alt_20;

  assign c$case_alt_20 = (counter_0 == 5'd21) ? (c$app_arg_6[1055 : 1008]) : c$case_alt_21;

  assign c$case_alt_21 = (counter_0 == 5'd22) ? (c$app_arg_6[1103 : 1056]) : c$case_alt_22;

  assign c$case_alt_22 = (counter_0 == 5'd23) ? (c$app_arg_6[1151 : 1104]) : c$case_alt_23;

  assign c$case_alt_23 = (counter_0 == 5'd24) ? (c$app_arg_6[1199 : 1152]) : c$case_alt_24;

  assign c$case_alt_24 = (counter_0 == 5'd25) ? (c$app_arg_6[1247 : 1200]) : c$case_alt_25;

  assign c$case_alt_25 = (counter_0 == 5'd26) ? (c$app_arg_6[1295 : 1248]) : c$case_alt_26;

  assign c$case_alt_26 = (counter_0 == 5'd27) ? (c$app_arg_6[1343 : 1296]) : ({48 {1'bx}});

  assign c$app_arg_6 = state;

  assign c$case_alt_27 = msgValid ? {{{2'b01,5'd0}
                                     ,result_6}
                                    ,{1'b0
                                     ,{48'b000000000000000000000000000000000000000000000000
                                      ,1'b0
                                      ,1'b0}}} : {c$ds_app_arg
                                                 ,{1'b1
                                                  ,{48'b000000000000000000000000000000000000000000000000
                                                   ,1'b0
                                                   ,1'b0}}};

  always_comb begin
    case(phase[6:5])
      2'b00 : c$case_alt_28 = c$case_alt_27;
      2'b01 : c$case_alt_28 = result_7;
      default : c$case_alt_28 = {c$app_arg_5
                                ,{1'b0,{result_8,1'b1,1'b0}}};
    endcase
  end

  assign phase = c$ds_app_arg.State_sel0;

  assign state = c$ds_app_arg.State_sel1;

  assign tready = c$arg.Tuple2_4_sel1;

  assign inputMsg = c$arg[274:3];

  assign msgValid = c$arg[2:2];

  assign counter = phase[4:0];

  assign counter_0 = phase[4:0];

  assign result = {result_0.Tuple2_2_sel1
                  ,result_0.Tuple2_2_sel0};

  assign XOF = result.Tuple2_5_sel0;

  assign MSG_TREADY = result.Tuple2_5_sel1;

  assign XOF_TDATA = XOF.AXI4Stream_sel0;

  assign XOF_TVALID = XOF.AXI4Stream_sel1;

  assign XOF_TLAST = XOF.AXI4Stream_sel2;


endmodule

