/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module dut
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [263:0] MSG_TDATA
    , input wire logic MSG_TVALID
    , input wire logic MSG_TLAST
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [11:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    , output logic DIGEST_TLAST
    , output logic MSG_TREADY
    );
  logic [1757:0] c$ds_app_arg = {2'b00,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  dut_types::Tuple2_2 result_0;
  dut_types::Tuple2_3 c$case_alt;
  dut_types::AXI4Stream c$app_arg;
  logic [11:0] result_1;
  logic [2:0] a;
  logic [2:0] b;
  logic [5:0] c$b_app_arg;
  logic [1757:0] c$app_arg_0;
  logic [1757:0] result_2;
  logic [1757:0] c$case_alt_0;
  logic signed [63:0] ds2;
  logic signed [63:0] c$ds2_app_arg;
  logic [63:0] result_3;
  logic [63:0] c$case_alt_1;
  logic [63:0] c$case_alt_2;
  logic [63:0] c$case_alt_3;
  logic [63:0] c$case_alt_4;
  logic [63:0] c$case_alt_5;
  logic [63:0] c$case_alt_6;
  logic [63:0] c$case_alt_7;
  logic [63:0] c$case_alt_8;
  logic [63:0] c$case_alt_9;
  logic [63:0] c$case_alt_10;
  logic [63:0] c$case_alt_11;
  logic [63:0] c$case_alt_12;
  logic [63:0] c$case_alt_13;
  logic [63:0] c$case_alt_14;
  logic [63:0] c$case_alt_15;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] state;
  logic signed [63:0] c$karg_app_arg;
  logic signed [63:0] c$karg_case_alt;
  logic signed [63:0] c$karg_case_alt_0;
  logic needLoad;
  logic [0:0] blockIdx;
  logic [4:0] wordIdx;
  logic [7:0] \validBits' ;
  dut_types::Tuple3_0 ds1;
  logic canOutput;
  logic [7:0] validBits;
  logic [127:0] buffer;
  logic isLast;
  logic [8:0] coeffIdx;
  logic tready;
  dut_types::Tuple2_3 result_4;
  logic [7:0] validBits_0;
  logic [127:0] buffer_0;
  logic [0:0] blockIdx_0;
  logic [4:0] wordIdx_0;
  logic [8:0] coeffIdx_0;
  dut_types::Tuple2_3 c$case_alt_16;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_7;
  logic [1599:0] c$app_arg_4;
  logic [1599:0] result_8;
  logic [1599:0] c$app_arg_5;
  logic [1599:0] result_9;
  logic [1599:0] c$app_arg_6;
  logic [1599:0] result_10;
  logic [1599:0] c$app_arg_7;
  dut_types::AXI4Stream_0 inBeat;
  logic [1599:0] c$keccakF1600Reversed_out;
  logic [1599:0] state_0;
  logic [4:0] roundIdx;
  dut_types::Tuple2_4 c$arg;
  logic [0:0] c$bv;
  logic [0:0] c$bv_0;
  logic [0:0] c$bv_1;
  logic [0:0] c$bv_2;
  logic [0:0] c$bv_3;
  logic [0:0] c$bv_4;
  logic [127:0] c$bv_5;
  logic [7:0] c$i_12;
  logic [4:0] c$i_31;
  dut_types::Tuple2_5 result;
  dut_types::AXI4Stream DIGEST;

  assign c$arg = {{MSG_TDATA
                  ,MSG_TVALID
                  ,MSG_TLAST}
                 ,DIGEST_TREADY};

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {2'b00,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt.Tuple2_3_sel0;
    end
  end
  // register end

  assign result_0 = c$case_alt.Tuple2_3_sel1;

  always_comb begin
    case(c$ds_app_arg[1757:1756])
      2'b00 : c$case_alt = c$case_alt_16;
      2'b01 : c$case_alt = result_4;
      2'b10 : c$case_alt = {c$app_arg_0
                           ,{1'b0,c$app_arg}};
      default : c$case_alt = {{2'b11,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                             ,{1'b0,{12'b000000000000,1'b0,1'b0}}};
    endcase
  end

  assign c$app_arg = canOutput ? {result_1
                                 ,1'b1
                                 ,isLast} : {12'b000000000000,1'b0,1'b0};

  assign result_1 = (a >= b) ? ({9'b000000000,(((a - b)))}) : (12'b110100000001 - ({9'b000000000,(((b - a)))}));

  assign c$bv = ((c$b_app_arg[0 : 0]));

  assign c$bv_0 = ((c$b_app_arg[1 : 1]));

  assign c$bv_1 = ((c$b_app_arg[2 : 2]));

  assign a = (({{(3-1) {1'b0}},((c$b_app_arg[0 : 0]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[1 : 1]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[2 : 2]))});

  assign c$bv_2 = ((c$b_app_arg[3 : 3]));

  assign c$bv_3 = ((c$b_app_arg[4 : 4]));

  assign c$bv_4 = ((c$b_app_arg[5 : 5]));

  assign b = (({{(3-1) {1'b0}},((c$b_app_arg[3 : 3]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[4 : 4]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[5 : 5]))});

  assign c$bv_5 = (buffer);

  assign c$b_app_arg = (c$bv_5[127 : 122]);

  assign c$app_arg_0 = (canOutput & (tready & isLast)) ? {2'b11,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : result_2;

  assign result_2 = ((wordIdx == 5'd17) & ((blockIdx == 1'd0) & needLoad)) ? {2'b01,5'd0,ds1.Tuple3_0_sel0,wordIdx,1'd1,ds1.Tuple3_0_sel1,\validBits' ,state} : c$case_alt_0;

  assign c$case_alt_0 = needLoad ? {2'b10,ds1.Tuple3_0_sel0,wordIdx + 5'd1,blockIdx,ds1.Tuple3_0_sel1 | (({64'b0000000000000000000000000000000000000000000000000000000000000000,result_3}) << (ds2)),\validBits'  + 8'd64,state,5'bxxxxx} : {2'b10,ds1.Tuple3_0_sel0,wordIdx,blockIdx,ds1.Tuple3_0_sel1,\validBits' ,state,5'bxxxxx};

  assign ds2 = $signed(c$ds2_app_arg);

  assign c$i_12 = (8'd64 - \validBits' );

  assign c$ds2_app_arg = $unsigned({{(64-8) {1'b0}},c$i_12});

  assign result_3 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd0) ? (c$app_arg_1[1599 : 1536]) : c$case_alt_1;

  assign c$case_alt_1 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd1) ? (c$app_arg_1[1535 : 1472]) : c$case_alt_2;

  assign c$case_alt_2 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd2) ? (c$app_arg_1[1471 : 1408]) : c$case_alt_3;

  assign c$case_alt_3 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd3) ? (c$app_arg_1[1407 : 1344]) : c$case_alt_4;

  assign c$case_alt_4 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd4) ? (c$app_arg_1[1343 : 1280]) : c$case_alt_5;

  assign c$case_alt_5 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd5) ? (c$app_arg_1[1279 : 1216]) : c$case_alt_6;

  assign c$case_alt_6 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd6) ? (c$app_arg_1[1215 : 1152]) : c$case_alt_7;

  assign c$case_alt_7 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd7) ? (c$app_arg_1[1151 : 1088]) : c$case_alt_8;

  assign c$case_alt_8 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd8) ? (c$app_arg_1[1087 : 1024]) : c$case_alt_9;

  assign c$case_alt_9 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd9) ? (c$app_arg_1[1023 : 960]) : c$case_alt_10;

  assign c$case_alt_10 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd10) ? (c$app_arg_1[959 : 896]) : c$case_alt_11;

  assign c$case_alt_11 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd11) ? (c$app_arg_1[895 : 832]) : c$case_alt_12;

  assign c$case_alt_12 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd12) ? (c$app_arg_1[831 : 768]) : c$case_alt_13;

  assign c$case_alt_13 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd13) ? (c$app_arg_1[767 : 704]) : c$case_alt_14;

  assign c$case_alt_14 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd14) ? (c$app_arg_1[703 : 640]) : c$case_alt_15;

  assign c$case_alt_15 = (($unsigned(c$karg_app_arg[0+:5])) == 5'd15) ? (c$app_arg_1[639 : 576]) : (c$app_arg_1[575 : 512]);

  assign c$app_arg_1 = state;

  assign state = c$ds_app_arg[1604:5];

  assign c$karg_app_arg = (wordIdx < 5'd17) ? c$karg_case_alt : c$karg_case_alt_0;

  assign c$karg_case_alt = $unsigned({{(64-5) {1'b0}},wordIdx});

  assign c$i_31 = (wordIdx - 5'd17);

  assign c$karg_case_alt_0 = $unsigned({{(64-5) {1'b0}},c$i_31});

  assign needLoad = (\validBits'  <= 8'd64) & (wordIdx < 5'd24);

  assign blockIdx = c$ds_app_arg[1741:1741];

  assign wordIdx = c$ds_app_arg[1746:1742];

  assign \validBits'  = ds1.Tuple3_0_sel2;

  assign ds1 = (canOutput & tready) ? {coeffIdx + 9'd1
                                      ,buffer << (64'sd6)
                                      ,validBits - 8'd6} : {coeffIdx
                                                           ,buffer
                                                           ,validBits};

  assign canOutput = validBits >= 8'd6;

  assign validBits = c$ds_app_arg[1612:1605];

  assign buffer = c$ds_app_arg[1740:1613];

  assign isLast = coeffIdx == 9'd255;

  assign coeffIdx = c$ds_app_arg[1755:1747];

  assign tready = c$arg.Tuple2_4_sel1;

  assign result_4 = (roundIdx == 5'd23) ? {{2'b10,coeffIdx_0,wordIdx_0,blockIdx_0,buffer_0,validBits_0,c$keccakF1600Reversed_out,5'bxxxxx}
                                          ,{1'b0
                                           ,{12'b000000000000
                                            ,1'b0
                                            ,1'b0}}} : {{2'b01,roundIdx + 5'd1,coeffIdx_0,wordIdx_0,blockIdx_0,buffer_0,validBits_0,c$keccakF1600Reversed_out}
                                                       ,{1'b0,{12'b000000000000,1'b0,1'b0}}};

  assign validBits_0 = c$ds_app_arg[1607:1600];

  assign buffer_0 = c$ds_app_arg[1735:1608];

  assign blockIdx_0 = c$ds_app_arg[1736:1736];

  assign wordIdx_0 = c$ds_app_arg[1741:1737];

  assign coeffIdx_0 = c$ds_app_arg[1750:1742];

  assign c$case_alt_16 = inBeat.AXI4Stream_0_sel1 ? {{2'b01,5'd0,9'd0,5'd0,1'd0,128'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,8'd0,result_10}
                                                    ,{1'b0
                                                     ,{12'b000000000000
                                                      ,1'b0
                                                      ,1'b0}}} : {{2'b00,1756'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                                                 ,{1'b1,{12'b000000000000,1'b0,1'b0}}};

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_2;
    result_5[64'sd1331] = (~ (c$app_arg_2[64'sd1331]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_3;
    result_6[64'sd1332] = (~ (c$app_arg_3[64'sd1332]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_7;

  // replaceBit start
  always_comb begin
    result_7 = c$app_arg_4;
    result_7[64'sd1333] = (~ (c$app_arg_4[64'sd1333]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_8;

  // replaceBit start
  always_comb begin
    result_8 = c$app_arg_5;
    result_8[64'sd1334] = (~ (c$app_arg_5[64'sd1334]));
  end
  // replaceBit end

  assign c$app_arg_5 = result_9;

  // replaceBit start
  always_comb begin
    result_9 = c$app_arg_6;
    result_9[64'sd1335] = (~ (c$app_arg_6[64'sd1335]));
  end
  // replaceBit end

  assign c$app_arg_6 = ({inBeat.AXI4Stream_0_sel0,1336'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000});

  // replaceBit start
  always_comb begin
    result_10 = c$app_arg_7;
    result_10[64'sd512] = (~ (c$app_arg_7[64'sd512]));
  end
  // replaceBit end

  assign c$app_arg_7 = result_5;

  assign inBeat = c$arg.Tuple2_4_sel0;

  Component_SamplePolyCBD3_i264o12_keccakF1600Reversed Component_SamplePolyCBD3_i264o12_keccakF1600Reversed_c$keccakF1600Reversed_out
    ( .result (c$keccakF1600Reversed_out)
    , .roundIdx (roundIdx)
    , .x (state_0) );

  assign state_0 = c$ds_app_arg[1599:0];

  assign roundIdx = c$ds_app_arg[1755:1751];

  assign result = {result_0.Tuple2_2_sel1
                  ,result_0.Tuple2_2_sel0};

  assign DIGEST = result.Tuple2_5_sel0;

  assign MSG_TREADY = result.Tuple2_5_sel1;

  assign DIGEST_TDATA = DIGEST.AXI4Stream_sel0;

  assign DIGEST_TVALID = DIGEST.AXI4Stream_sel1;

  assign DIGEST_TLAST = DIGEST.AXI4Stream_sel2;


endmodule

