/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Component_SamplePolyCBD512
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [263:0] MSG_33B
    , input wire logic DIGEST_TREADY

      // Outputs
    , output logic [13:0] DIGEST_TDATA
    , output logic DIGEST_TVALID
    );
  logic [1617:0] c$ds_app_arg = {2'b00,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  Component_SamplePolyCBD512_types::Tuple2_2 c$case_alt;
  Component_SamplePolyCBD512_types::Tuple2_2 result_0;
  Component_SamplePolyCBD512_types::Tuple2_2 c$case_alt_0;
  logic [1617:0] c$$j_app_arg;
  logic [1617:0] c$$j_case_alt;
  logic isLast;
  Component_SamplePolyCBD512_types::Tuple4 result_1;
  logic [11:0] result_2;
  logic [2:0] a;
  logic [2:0] b;
  logic [5:0] c$b_app_arg;
  Component_SamplePolyCBD512_types::Tuple2_2 result_3;
  logic [2:0] phase;
  logic [7:0] idx;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_0;
  logic [1599:0] result_6;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_7;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_8;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_9;
  logic [1599:0] c$app_arg_4;
  logic [5:0] c$cbdDiff6_arg0;
  logic [5:0] c$cbdDiff6_arg0_case_alt;
  logic [1:0] tail2;
  logic [2:0] phase_0;
  logic [1599:0] c$cbdDiff6_arg0_app_arg;
  logic [5:0] result_10;
  logic [5:0] c$case_alt_1;
  logic [5:0] c$case_alt_2;
  logic [5:0] c$case_alt_3;
  logic [5:0] c$case_alt_4;
  logic [5:0] c$case_alt_5;
  logic [5:0] c$case_alt_6;
  logic [5:0] c$case_alt_7;
  logic [5:0] c$case_alt_8;
  logic [5:0] c$case_alt_9;
  logic [5:0] c$case_alt_10;
  logic [5:0] c$case_alt_11;
  logic [5:0] c$case_alt_12;
  logic [5:0] c$case_alt_13;
  logic [5:0] c$case_alt_14;
  logic [5:0] c$case_alt_15;
  logic [5:0] c$case_alt_16;
  logic [5:0] c$case_alt_17;
  logic [5:0] c$case_alt_18;
  logic [5:0] c$case_alt_19;
  logic [5:0] c$case_alt_20;
  logic [5:0] c$case_alt_21;
  logic [5:0] c$case_alt_22;
  logic [5:0] c$case_alt_23;
  logic [5:0] c$case_alt_24;
  logic [5:0] c$case_alt_25;
  logic [5:0] c$case_alt_26;
  logic [5:0] c$case_alt_27;
  logic [5:0] c$case_alt_28;
  logic [5:0] c$case_alt_29;
  logic [5:0] c$case_alt_30;
  logic [5:0] c$case_alt_31;
  logic [5:0] c$case_alt_32;
  logic [5:0] c$case_alt_33;
  logic [5:0] c$case_alt_34;
  logic [5:0] c$case_alt_35;
  logic [5:0] c$case_alt_36;
  logic [5:0] c$case_alt_37;
  logic [5:0] c$case_alt_38;
  logic [5:0] c$case_alt_39;
  logic [5:0] c$case_alt_40;
  logic [5:0] c$case_alt_41;
  logic [5:0] c$case_alt_42;
  logic [5:0] c$case_alt_43;
  logic [5:0] c$case_alt_44;
  logic [5:0] c$case_alt_45;
  logic [5:0] c$case_alt_46;
  logic [5:0] c$case_alt_47;
  logic [5:0] c$case_alt_48;
  logic [5:0] c$case_alt_49;
  logic [5:0] c$case_alt_50;
  logic [5:0] c$case_alt_51;
  logic [5:0] c$case_alt_52;
  logic [5:0] c$case_alt_53;
  logic [5:0] c$case_alt_54;
  logic [5:0] c$case_alt_55;
  logic [5:0] c$case_alt_56;
  logic [5:0] c$case_alt_57;
  logic [5:0] c$case_alt_58;
  logic [5:0] c$case_alt_59;
  logic [5:0] c$case_alt_60;
  logic [5:0] c$case_alt_61;
  logic [5:0] c$case_alt_62;
  logic [5:0] c$case_alt_63;
  logic [5:0] c$case_alt_64;
  logic [5:0] c$case_alt_65;
  logic [5:0] c$case_alt_66;
  logic [5:0] c$case_alt_67;
  logic [5:0] c$case_alt_68;
  logic [5:0] c$case_alt_69;
  logic [5:0] c$case_alt_70;
  logic [5:0] c$case_alt_71;
  logic [5:0] c$case_alt_72;
  logic [5:0] c$case_alt_73;
  logic [1599:0] c$app_arg_5;
  logic signed [63:0] c$cbdDiff6_arg0_app_arg_0;
  logic [5:0] result_11;
  logic [5:0] c$case_alt_74;
  logic [5:0] c$case_alt_75;
  logic [5:0] c$case_alt_76;
  logic [5:0] c$case_alt_77;
  logic [5:0] c$case_alt_78;
  logic [5:0] c$case_alt_79;
  logic [5:0] c$case_alt_80;
  logic [5:0] c$case_alt_81;
  logic [5:0] c$case_alt_82;
  logic [5:0] c$case_alt_83;
  logic [5:0] c$case_alt_84;
  logic [5:0] c$case_alt_85;
  logic [5:0] c$case_alt_86;
  logic [5:0] c$case_alt_87;
  logic [5:0] c$case_alt_88;
  logic [5:0] c$case_alt_89;
  logic [5:0] c$case_alt_90;
  logic [5:0] c$case_alt_91;
  logic [5:0] c$case_alt_92;
  logic [5:0] c$case_alt_93;
  logic [5:0] c$case_alt_94;
  logic [5:0] c$case_alt_95;
  logic [5:0] c$case_alt_96;
  logic [5:0] c$case_alt_97;
  logic [5:0] c$case_alt_98;
  logic [5:0] c$case_alt_99;
  logic [5:0] c$case_alt_100;
  logic [5:0] c$case_alt_101;
  logic [5:0] c$case_alt_102;
  logic [5:0] c$case_alt_103;
  logic [5:0] c$case_alt_104;
  logic [5:0] c$case_alt_105;
  logic [5:0] c$case_alt_106;
  logic [5:0] c$case_alt_107;
  logic [5:0] c$case_alt_108;
  logic [5:0] c$case_alt_109;
  logic [5:0] c$case_alt_110;
  logic [5:0] c$case_alt_111;
  logic [5:0] c$case_alt_112;
  logic [5:0] c$case_alt_113;
  logic [5:0] c$case_alt_114;
  logic [5:0] c$case_alt_115;
  logic [5:0] c$case_alt_116;
  logic [5:0] c$case_alt_117;
  logic [5:0] c$case_alt_118;
  logic [5:0] c$case_alt_119;
  logic [5:0] c$case_alt_120;
  logic [5:0] c$case_alt_121;
  logic [5:0] c$case_alt_122;
  logic [5:0] c$case_alt_123;
  logic [5:0] c$case_alt_124;
  logic [5:0] c$case_alt_125;
  logic [5:0] c$case_alt_126;
  logic [5:0] c$case_alt_127;
  logic [5:0] c$case_alt_128;
  logic [5:0] c$case_alt_129;
  logic [5:0] c$case_alt_130;
  logic [5:0] c$case_alt_131;
  logic [5:0] c$case_alt_132;
  logic [5:0] c$case_alt_133;
  logic [5:0] c$case_alt_134;
  logic [5:0] c$case_alt_135;
  logic [5:0] c$case_alt_136;
  logic [5:0] c$case_alt_137;
  logic [5:0] c$case_alt_138;
  logic [5:0] c$case_alt_139;
  logic [5:0] c$case_alt_140;
  logic [5:0] c$case_alt_141;
  logic [5:0] c$case_alt_142;
  logic [5:0] c$case_alt_143;
  logic [5:0] c$case_alt_144;
  logic [5:0] c$case_alt_145;
  logic [5:0] c$case_alt_146;
  logic [5:0] c$case_alt_147;
  logic [5:0] c$case_alt_148;
  logic [5:0] c$case_alt_149;
  logic [5:0] c$case_alt_150;
  logic [5:0] c$case_alt_151;
  logic [5:0] c$case_alt_152;
  logic [5:0] c$case_alt_153;
  logic [5:0] c$case_alt_154;
  logic [5:0] c$case_alt_155;
  logic [5:0] c$case_alt_156;
  logic [5:0] c$case_alt_157;
  logic [5:0] c$case_alt_158;
  logic [5:0] c$case_alt_159;
  logic [5:0] c$case_alt_160;
  logic [5:0] c$case_alt_161;
  logic [5:0] c$case_alt_162;
  logic [5:0] c$case_alt_163;
  logic [5:0] c$case_alt_164;
  logic [5:0] c$case_alt_165;
  logic [5:0] c$case_alt_166;
  logic [5:0] c$case_alt_167;
  logic [5:0] c$case_alt_168;
  logic [5:0] c$case_alt_169;
  logic [5:0] c$case_alt_170;
  logic [5:0] c$case_alt_171;
  logic [5:0] c$case_alt_172;
  logic [5:0] c$case_alt_173;
  logic [5:0] c$case_alt_174;
  logic [5:0] c$case_alt_175;
  logic [5:0] c$case_alt_176;
  logic [5:0] c$case_alt_177;
  logic [5:0] c$case_alt_178;
  logic [5:0] c$case_alt_179;
  logic [5:0] c$case_alt_180;
  logic [5:0] c$case_alt_181;
  logic [5:0] c$case_alt_182;
  logic [5:0] c$case_alt_183;
  logic [5:0] c$case_alt_184;
  logic [5:0] c$case_alt_185;
  logic [5:0] c$case_alt_186;
  logic [5:0] c$case_alt_187;
  logic [5:0] c$case_alt_188;
  logic [5:0] c$case_alt_189;
  logic [5:0] c$case_alt_190;
  logic [5:0] c$case_alt_191;
  logic [5:0] c$case_alt_192;
  logic [5:0] c$case_alt_193;
  logic [5:0] c$case_alt_194;
  logic [5:0] c$case_alt_195;
  logic [5:0] c$case_alt_196;
  logic [5:0] c$case_alt_197;
  logic [5:0] c$case_alt_198;
  logic [5:0] c$case_alt_199;
  logic [5:0] c$case_alt_200;
  logic [5:0] c$case_alt_201;
  logic [5:0] c$case_alt_202;
  logic [5:0] c$case_alt_203;
  logic [5:0] c$case_alt_204;
  logic [5:0] c$case_alt_205;
  logic [5:0] c$case_alt_206;
  logic [5:0] c$case_alt_207;
  logic [5:0] c$case_alt_208;
  logic [5:0] c$case_alt_209;
  logic [5:0] c$case_alt_210;
  logic [5:0] c$case_alt_211;
  logic [5:0] c$case_alt_212;
  logic [5:0] c$case_alt_213;
  logic [5:0] c$case_alt_214;
  logic [5:0] c$case_alt_215;
  logic [5:0] c$case_alt_216;
  logic [5:0] c$case_alt_217;
  logic [5:0] c$case_alt_218;
  logic [5:0] c$case_alt_219;
  logic [5:0] c$case_alt_220;
  logic [5:0] c$case_alt_221;
  logic [5:0] c$case_alt_222;
  logic [5:0] c$case_alt_223;
  logic [5:0] c$case_alt_224;
  logic [5:0] c$case_alt_225;
  logic [5:0] c$case_alt_226;
  logic [5:0] c$case_alt_227;
  logic [5:0] c$case_alt_228;
  logic [5:0] c$case_alt_229;
  logic [5:0] c$case_alt_230;
  logic [5:0] c$case_alt_231;
  logic [5:0] c$case_alt_232;
  logic [5:0] c$case_alt_233;
  logic [5:0] c$case_alt_234;
  logic [5:0] c$case_alt_235;
  logic [5:0] c$case_alt_236;
  logic [5:0] c$case_alt_237;
  logic [5:0] c$case_alt_238;
  logic [5:0] c$case_alt_239;
  logic [5:0] c$case_alt_240;
  logic [5:0] c$case_alt_241;
  logic [5:0] c$case_alt_242;
  logic [5:0] c$case_alt_243;
  logic [5:0] c$case_alt_244;
  logic [5:0] c$case_alt_245;
  logic [5:0] c$case_alt_246;
  logic [5:0] c$case_alt_247;
  logic [5:0] c$case_alt_248;
  logic [5:0] c$case_alt_249;
  logic [5:0] c$case_alt_250;
  logic [5:0] c$case_alt_251;
  logic [5:0] c$case_alt_252;
  logic [5:0] c$case_alt_253;
  logic [1599:0] c$app_arg_6;
  logic [1599:0] block;
  logic signed [63:0] c$cbdDiff6_arg0_app_arg_1;
  logic [7:0] idx_0;
  logic [1599:0] c$keccakF1600_out;
  logic [1599:0] state;
  logic [4:0] roundIdx;
  logic [0:0] c$bv;
  logic [0:0] c$bv_0;
  logic [0:0] c$bv_1;
  logic [0:0] c$bv_2;
  logic [0:0] c$bv_3;
  logic [0:0] c$bv_4;
  logic [7:0] c$i_92;
  Component_SamplePolyCBD512_types::Tuple2_3 result;
  Component_SamplePolyCBD512_types::AXI4Stream DIGEST_TDATA_0;

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds_app_arg_register
    if ( RST) begin
      c$ds_app_arg <= {2'b00,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds_app_arg <= c$case_alt.Tuple2_2_sel0;
    end
  end
  // register end

  assign result = c$case_alt.Tuple2_2_sel1;

  always_comb begin
    case(c$ds_app_arg[1617:1616])
      2'b00 : c$case_alt = {{2'b01,5'd0,8'd0,result_4,{1'b0,2'bxx}}
                           ,{{12'b000000000000,1'b0,1'b0},1'b1}};
      2'b01 : c$case_alt = result_3;
      2'b10 : c$case_alt = result_0;
      default : c$case_alt = {{2'b11,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                             ,{{12'b000000000000,1'b0,1'b0},1'b0}};
    endcase
  end

  assign result_0 = phase_0[2:2] ? {c$$j_app_arg
                                   ,{{result_1.Tuple4_sel0,1'b1,isLast}
                                    ,1'b0}} : c$case_alt_0;

  assign c$case_alt_0 = (idx_0 >= 8'd181) ? {{2'b01,5'd0,idx_0,block,{1'b1,c$cbdDiff6_arg0_app_arg[1087 : 1086]}}
                                            ,{{12'b000000000000,1'b0,1'b0}
                                             ,1'b0}} : {c$$j_app_arg
                                                       ,{{result_1.Tuple4_sel0,1'b1,isLast},1'b0}};

  assign c$$j_app_arg = (DIGEST_TREADY & isLast) ? {2'b11,1616'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx} : c$$j_case_alt;

  assign c$$j_case_alt = DIGEST_TREADY ? {2'b10,idx_0 + 8'd1,block,result_1.Tuple4_sel3,5'bxxxxx} : {2'b10,idx_0,block,result_1.Tuple4_sel2,5'bxxxxx};

  assign isLast = result_1.Tuple4_sel1;

  assign result_1 = phase_0[2:2] ? {result_2
                                   ,idx_0 == 8'd255
                                   ,phase_0
                                   ,phase_0} : {result_2
                                               ,1'b0
                                               ,{1'b0,2'bxx}
                                               ,{1'b0,2'bxx}};

  assign result_2 = (a >= b) ? ({9'b000000000,(((a - b)))}) : (12'b110100000001 - ({9'b000000000,(((b - a)))}));

  assign c$bv = ((c$b_app_arg[0 : 0]));

  assign c$bv_0 = ((c$b_app_arg[1 : 1]));

  assign c$bv_1 = ((c$b_app_arg[2 : 2]));

  assign a = (({{(3-1) {1'b0}},((c$b_app_arg[0 : 0]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[1 : 1]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[2 : 2]))});

  assign c$bv_2 = ((c$b_app_arg[3 : 3]));

  assign c$bv_3 = ((c$b_app_arg[4 : 4]));

  assign c$bv_4 = ((c$b_app_arg[5 : 5]));

  assign b = (({{(3-1) {1'b0}},((c$b_app_arg[3 : 3]))}) + ({{(3-1) {1'b0}},((c$b_app_arg[4 : 4]))})) + ({{(3-1) {1'b0}},((c$b_app_arg[5 : 5]))});

  assign c$b_app_arg = c$cbdDiff6_arg0;

  assign result_3 = (roundIdx == 5'd23) ? {{2'b10,idx,c$keccakF1600_out,phase,5'bxxxxx}
                                          ,{{12'b000000000000,1'b0,1'b0}
                                           ,1'b0}} : {{2'b01,roundIdx + 5'd1,idx,c$keccakF1600_out,phase}
                                                     ,{{12'b000000000000,1'b0,1'b0},1'b0}};

  assign phase = c$ds_app_arg[2:0];

  assign idx = c$ds_app_arg[1610:1603];

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg;
    result_4[64'sd1087] = (~ (c$app_arg[64'sd1087]));
  end
  // replaceBit end

  assign c$app_arg = result_5;

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_0;
    result_5[64'sd264] = (~ (c$app_arg_0[64'sd264]));
  end
  // replaceBit end

  assign c$app_arg_0 = result_6;

  // replaceBit start
  always_comb begin
    result_6 = c$app_arg_1;
    result_6[64'sd265] = (~ (c$app_arg_1[64'sd265]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_7;

  // replaceBit start
  always_comb begin
    result_7 = c$app_arg_2;
    result_7[64'sd266] = (~ (c$app_arg_2[64'sd266]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_8;

  // replaceBit start
  always_comb begin
    result_8 = c$app_arg_3;
    result_8[64'sd267] = (~ (c$app_arg_3[64'sd267]));
  end
  // replaceBit end

  assign c$app_arg_3 = result_9;

  // replaceBit start
  always_comb begin
    result_9 = c$app_arg_4;
    result_9[64'sd268] = (~ (c$app_arg_4[64'sd268]));
  end
  // replaceBit end

  assign c$app_arg_4 = ({1336'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,MSG_33B});

  assign c$cbdDiff6_arg0 = phase_0[2:2] ? c$cbdDiff6_arg0_case_alt : result_11;

  assign c$cbdDiff6_arg0_case_alt = (idx_0 == 8'd181) ? ({(c$cbdDiff6_arg0_app_arg[3 : 0]),tail2}) : result_10;

  assign tail2 = phase_0[1:0];

  assign phase_0 = c$ds_app_arg[7:5];

  assign c$cbdDiff6_arg0_app_arg = block;

  assign result_10 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd0) ? (c$app_arg_5[9 : 4]) : c$case_alt_1;

  assign c$case_alt_1 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd1) ? (c$app_arg_5[15 : 10]) : c$case_alt_2;

  assign c$case_alt_2 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd2) ? (c$app_arg_5[21 : 16]) : c$case_alt_3;

  assign c$case_alt_3 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd3) ? (c$app_arg_5[27 : 22]) : c$case_alt_4;

  assign c$case_alt_4 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd4) ? (c$app_arg_5[33 : 28]) : c$case_alt_5;

  assign c$case_alt_5 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd5) ? (c$app_arg_5[39 : 34]) : c$case_alt_6;

  assign c$case_alt_6 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd6) ? (c$app_arg_5[45 : 40]) : c$case_alt_7;

  assign c$case_alt_7 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd7) ? (c$app_arg_5[51 : 46]) : c$case_alt_8;

  assign c$case_alt_8 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd8) ? (c$app_arg_5[57 : 52]) : c$case_alt_9;

  assign c$case_alt_9 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd9) ? (c$app_arg_5[63 : 58]) : c$case_alt_10;

  assign c$case_alt_10 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd10) ? (c$app_arg_5[69 : 64]) : c$case_alt_11;

  assign c$case_alt_11 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd11) ? (c$app_arg_5[75 : 70]) : c$case_alt_12;

  assign c$case_alt_12 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd12) ? (c$app_arg_5[81 : 76]) : c$case_alt_13;

  assign c$case_alt_13 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd13) ? (c$app_arg_5[87 : 82]) : c$case_alt_14;

  assign c$case_alt_14 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd14) ? (c$app_arg_5[93 : 88]) : c$case_alt_15;

  assign c$case_alt_15 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd15) ? (c$app_arg_5[99 : 94]) : c$case_alt_16;

  assign c$case_alt_16 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd16) ? (c$app_arg_5[105 : 100]) : c$case_alt_17;

  assign c$case_alt_17 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd17) ? (c$app_arg_5[111 : 106]) : c$case_alt_18;

  assign c$case_alt_18 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd18) ? (c$app_arg_5[117 : 112]) : c$case_alt_19;

  assign c$case_alt_19 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd19) ? (c$app_arg_5[123 : 118]) : c$case_alt_20;

  assign c$case_alt_20 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd20) ? (c$app_arg_5[129 : 124]) : c$case_alt_21;

  assign c$case_alt_21 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd21) ? (c$app_arg_5[135 : 130]) : c$case_alt_22;

  assign c$case_alt_22 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd22) ? (c$app_arg_5[141 : 136]) : c$case_alt_23;

  assign c$case_alt_23 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd23) ? (c$app_arg_5[147 : 142]) : c$case_alt_24;

  assign c$case_alt_24 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd24) ? (c$app_arg_5[153 : 148]) : c$case_alt_25;

  assign c$case_alt_25 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd25) ? (c$app_arg_5[159 : 154]) : c$case_alt_26;

  assign c$case_alt_26 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd26) ? (c$app_arg_5[165 : 160]) : c$case_alt_27;

  assign c$case_alt_27 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd27) ? (c$app_arg_5[171 : 166]) : c$case_alt_28;

  assign c$case_alt_28 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd28) ? (c$app_arg_5[177 : 172]) : c$case_alt_29;

  assign c$case_alt_29 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd29) ? (c$app_arg_5[183 : 178]) : c$case_alt_30;

  assign c$case_alt_30 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd30) ? (c$app_arg_5[189 : 184]) : c$case_alt_31;

  assign c$case_alt_31 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd31) ? (c$app_arg_5[195 : 190]) : c$case_alt_32;

  assign c$case_alt_32 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd32) ? (c$app_arg_5[201 : 196]) : c$case_alt_33;

  assign c$case_alt_33 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd33) ? (c$app_arg_5[207 : 202]) : c$case_alt_34;

  assign c$case_alt_34 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd34) ? (c$app_arg_5[213 : 208]) : c$case_alt_35;

  assign c$case_alt_35 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd35) ? (c$app_arg_5[219 : 214]) : c$case_alt_36;

  assign c$case_alt_36 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd36) ? (c$app_arg_5[225 : 220]) : c$case_alt_37;

  assign c$case_alt_37 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd37) ? (c$app_arg_5[231 : 226]) : c$case_alt_38;

  assign c$case_alt_38 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd38) ? (c$app_arg_5[237 : 232]) : c$case_alt_39;

  assign c$case_alt_39 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd39) ? (c$app_arg_5[243 : 238]) : c$case_alt_40;

  assign c$case_alt_40 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd40) ? (c$app_arg_5[249 : 244]) : c$case_alt_41;

  assign c$case_alt_41 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd41) ? (c$app_arg_5[255 : 250]) : c$case_alt_42;

  assign c$case_alt_42 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd42) ? (c$app_arg_5[261 : 256]) : c$case_alt_43;

  assign c$case_alt_43 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd43) ? (c$app_arg_5[267 : 262]) : c$case_alt_44;

  assign c$case_alt_44 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd44) ? (c$app_arg_5[273 : 268]) : c$case_alt_45;

  assign c$case_alt_45 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd45) ? (c$app_arg_5[279 : 274]) : c$case_alt_46;

  assign c$case_alt_46 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd46) ? (c$app_arg_5[285 : 280]) : c$case_alt_47;

  assign c$case_alt_47 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd47) ? (c$app_arg_5[291 : 286]) : c$case_alt_48;

  assign c$case_alt_48 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd48) ? (c$app_arg_5[297 : 292]) : c$case_alt_49;

  assign c$case_alt_49 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd49) ? (c$app_arg_5[303 : 298]) : c$case_alt_50;

  assign c$case_alt_50 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd50) ? (c$app_arg_5[309 : 304]) : c$case_alt_51;

  assign c$case_alt_51 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd51) ? (c$app_arg_5[315 : 310]) : c$case_alt_52;

  assign c$case_alt_52 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd52) ? (c$app_arg_5[321 : 316]) : c$case_alt_53;

  assign c$case_alt_53 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd53) ? (c$app_arg_5[327 : 322]) : c$case_alt_54;

  assign c$case_alt_54 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd54) ? (c$app_arg_5[333 : 328]) : c$case_alt_55;

  assign c$case_alt_55 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd55) ? (c$app_arg_5[339 : 334]) : c$case_alt_56;

  assign c$case_alt_56 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd56) ? (c$app_arg_5[345 : 340]) : c$case_alt_57;

  assign c$case_alt_57 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd57) ? (c$app_arg_5[351 : 346]) : c$case_alt_58;

  assign c$case_alt_58 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd58) ? (c$app_arg_5[357 : 352]) : c$case_alt_59;

  assign c$case_alt_59 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd59) ? (c$app_arg_5[363 : 358]) : c$case_alt_60;

  assign c$case_alt_60 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd60) ? (c$app_arg_5[369 : 364]) : c$case_alt_61;

  assign c$case_alt_61 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd61) ? (c$app_arg_5[375 : 370]) : c$case_alt_62;

  assign c$case_alt_62 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd62) ? (c$app_arg_5[381 : 376]) : c$case_alt_63;

  assign c$case_alt_63 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd63) ? (c$app_arg_5[387 : 382]) : c$case_alt_64;

  assign c$case_alt_64 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd64) ? (c$app_arg_5[393 : 388]) : c$case_alt_65;

  assign c$case_alt_65 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd65) ? (c$app_arg_5[399 : 394]) : c$case_alt_66;

  assign c$case_alt_66 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd66) ? (c$app_arg_5[405 : 400]) : c$case_alt_67;

  assign c$case_alt_67 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd67) ? (c$app_arg_5[411 : 406]) : c$case_alt_68;

  assign c$case_alt_68 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd68) ? (c$app_arg_5[417 : 412]) : c$case_alt_69;

  assign c$case_alt_69 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd69) ? (c$app_arg_5[423 : 418]) : c$case_alt_70;

  assign c$case_alt_70 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd70) ? (c$app_arg_5[429 : 424]) : c$case_alt_71;

  assign c$case_alt_71 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd71) ? (c$app_arg_5[435 : 430]) : c$case_alt_72;

  assign c$case_alt_72 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd72) ? (c$app_arg_5[441 : 436]) : c$case_alt_73;

  assign c$case_alt_73 = (($unsigned(c$cbdDiff6_arg0_app_arg_0[0+:7])) == 7'd73) ? (c$app_arg_5[447 : 442]) : ({6 {1'bx}});

  assign c$app_arg_5 = block;

  assign c$i_92 = (idx_0 - 8'd182);

  assign c$cbdDiff6_arg0_app_arg_0 = $unsigned({{(64-8) {1'b0}},c$i_92});

  assign result_11 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd0) ? (c$app_arg_6[5 : 0]) : c$case_alt_74;

  assign c$case_alt_74 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd1) ? (c$app_arg_6[11 : 6]) : c$case_alt_75;

  assign c$case_alt_75 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd2) ? (c$app_arg_6[17 : 12]) : c$case_alt_76;

  assign c$case_alt_76 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd3) ? (c$app_arg_6[23 : 18]) : c$case_alt_77;

  assign c$case_alt_77 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd4) ? (c$app_arg_6[29 : 24]) : c$case_alt_78;

  assign c$case_alt_78 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd5) ? (c$app_arg_6[35 : 30]) : c$case_alt_79;

  assign c$case_alt_79 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd6) ? (c$app_arg_6[41 : 36]) : c$case_alt_80;

  assign c$case_alt_80 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd7) ? (c$app_arg_6[47 : 42]) : c$case_alt_81;

  assign c$case_alt_81 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd8) ? (c$app_arg_6[53 : 48]) : c$case_alt_82;

  assign c$case_alt_82 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd9) ? (c$app_arg_6[59 : 54]) : c$case_alt_83;

  assign c$case_alt_83 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd10) ? (c$app_arg_6[65 : 60]) : c$case_alt_84;

  assign c$case_alt_84 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd11) ? (c$app_arg_6[71 : 66]) : c$case_alt_85;

  assign c$case_alt_85 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd12) ? (c$app_arg_6[77 : 72]) : c$case_alt_86;

  assign c$case_alt_86 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd13) ? (c$app_arg_6[83 : 78]) : c$case_alt_87;

  assign c$case_alt_87 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd14) ? (c$app_arg_6[89 : 84]) : c$case_alt_88;

  assign c$case_alt_88 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd15) ? (c$app_arg_6[95 : 90]) : c$case_alt_89;

  assign c$case_alt_89 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd16) ? (c$app_arg_6[101 : 96]) : c$case_alt_90;

  assign c$case_alt_90 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd17) ? (c$app_arg_6[107 : 102]) : c$case_alt_91;

  assign c$case_alt_91 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd18) ? (c$app_arg_6[113 : 108]) : c$case_alt_92;

  assign c$case_alt_92 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd19) ? (c$app_arg_6[119 : 114]) : c$case_alt_93;

  assign c$case_alt_93 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd20) ? (c$app_arg_6[125 : 120]) : c$case_alt_94;

  assign c$case_alt_94 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd21) ? (c$app_arg_6[131 : 126]) : c$case_alt_95;

  assign c$case_alt_95 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd22) ? (c$app_arg_6[137 : 132]) : c$case_alt_96;

  assign c$case_alt_96 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd23) ? (c$app_arg_6[143 : 138]) : c$case_alt_97;

  assign c$case_alt_97 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd24) ? (c$app_arg_6[149 : 144]) : c$case_alt_98;

  assign c$case_alt_98 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd25) ? (c$app_arg_6[155 : 150]) : c$case_alt_99;

  assign c$case_alt_99 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd26) ? (c$app_arg_6[161 : 156]) : c$case_alt_100;

  assign c$case_alt_100 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd27) ? (c$app_arg_6[167 : 162]) : c$case_alt_101;

  assign c$case_alt_101 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd28) ? (c$app_arg_6[173 : 168]) : c$case_alt_102;

  assign c$case_alt_102 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd29) ? (c$app_arg_6[179 : 174]) : c$case_alt_103;

  assign c$case_alt_103 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd30) ? (c$app_arg_6[185 : 180]) : c$case_alt_104;

  assign c$case_alt_104 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd31) ? (c$app_arg_6[191 : 186]) : c$case_alt_105;

  assign c$case_alt_105 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd32) ? (c$app_arg_6[197 : 192]) : c$case_alt_106;

  assign c$case_alt_106 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd33) ? (c$app_arg_6[203 : 198]) : c$case_alt_107;

  assign c$case_alt_107 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd34) ? (c$app_arg_6[209 : 204]) : c$case_alt_108;

  assign c$case_alt_108 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd35) ? (c$app_arg_6[215 : 210]) : c$case_alt_109;

  assign c$case_alt_109 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd36) ? (c$app_arg_6[221 : 216]) : c$case_alt_110;

  assign c$case_alt_110 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd37) ? (c$app_arg_6[227 : 222]) : c$case_alt_111;

  assign c$case_alt_111 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd38) ? (c$app_arg_6[233 : 228]) : c$case_alt_112;

  assign c$case_alt_112 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd39) ? (c$app_arg_6[239 : 234]) : c$case_alt_113;

  assign c$case_alt_113 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd40) ? (c$app_arg_6[245 : 240]) : c$case_alt_114;

  assign c$case_alt_114 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd41) ? (c$app_arg_6[251 : 246]) : c$case_alt_115;

  assign c$case_alt_115 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd42) ? (c$app_arg_6[257 : 252]) : c$case_alt_116;

  assign c$case_alt_116 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd43) ? (c$app_arg_6[263 : 258]) : c$case_alt_117;

  assign c$case_alt_117 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd44) ? (c$app_arg_6[269 : 264]) : c$case_alt_118;

  assign c$case_alt_118 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd45) ? (c$app_arg_6[275 : 270]) : c$case_alt_119;

  assign c$case_alt_119 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd46) ? (c$app_arg_6[281 : 276]) : c$case_alt_120;

  assign c$case_alt_120 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd47) ? (c$app_arg_6[287 : 282]) : c$case_alt_121;

  assign c$case_alt_121 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd48) ? (c$app_arg_6[293 : 288]) : c$case_alt_122;

  assign c$case_alt_122 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd49) ? (c$app_arg_6[299 : 294]) : c$case_alt_123;

  assign c$case_alt_123 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd50) ? (c$app_arg_6[305 : 300]) : c$case_alt_124;

  assign c$case_alt_124 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd51) ? (c$app_arg_6[311 : 306]) : c$case_alt_125;

  assign c$case_alt_125 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd52) ? (c$app_arg_6[317 : 312]) : c$case_alt_126;

  assign c$case_alt_126 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd53) ? (c$app_arg_6[323 : 318]) : c$case_alt_127;

  assign c$case_alt_127 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd54) ? (c$app_arg_6[329 : 324]) : c$case_alt_128;

  assign c$case_alt_128 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd55) ? (c$app_arg_6[335 : 330]) : c$case_alt_129;

  assign c$case_alt_129 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd56) ? (c$app_arg_6[341 : 336]) : c$case_alt_130;

  assign c$case_alt_130 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd57) ? (c$app_arg_6[347 : 342]) : c$case_alt_131;

  assign c$case_alt_131 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd58) ? (c$app_arg_6[353 : 348]) : c$case_alt_132;

  assign c$case_alt_132 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd59) ? (c$app_arg_6[359 : 354]) : c$case_alt_133;

  assign c$case_alt_133 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd60) ? (c$app_arg_6[365 : 360]) : c$case_alt_134;

  assign c$case_alt_134 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd61) ? (c$app_arg_6[371 : 366]) : c$case_alt_135;

  assign c$case_alt_135 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd62) ? (c$app_arg_6[377 : 372]) : c$case_alt_136;

  assign c$case_alt_136 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd63) ? (c$app_arg_6[383 : 378]) : c$case_alt_137;

  assign c$case_alt_137 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd64) ? (c$app_arg_6[389 : 384]) : c$case_alt_138;

  assign c$case_alt_138 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd65) ? (c$app_arg_6[395 : 390]) : c$case_alt_139;

  assign c$case_alt_139 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd66) ? (c$app_arg_6[401 : 396]) : c$case_alt_140;

  assign c$case_alt_140 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd67) ? (c$app_arg_6[407 : 402]) : c$case_alt_141;

  assign c$case_alt_141 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd68) ? (c$app_arg_6[413 : 408]) : c$case_alt_142;

  assign c$case_alt_142 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd69) ? (c$app_arg_6[419 : 414]) : c$case_alt_143;

  assign c$case_alt_143 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd70) ? (c$app_arg_6[425 : 420]) : c$case_alt_144;

  assign c$case_alt_144 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd71) ? (c$app_arg_6[431 : 426]) : c$case_alt_145;

  assign c$case_alt_145 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd72) ? (c$app_arg_6[437 : 432]) : c$case_alt_146;

  assign c$case_alt_146 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd73) ? (c$app_arg_6[443 : 438]) : c$case_alt_147;

  assign c$case_alt_147 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd74) ? (c$app_arg_6[449 : 444]) : c$case_alt_148;

  assign c$case_alt_148 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd75) ? (c$app_arg_6[455 : 450]) : c$case_alt_149;

  assign c$case_alt_149 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd76) ? (c$app_arg_6[461 : 456]) : c$case_alt_150;

  assign c$case_alt_150 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd77) ? (c$app_arg_6[467 : 462]) : c$case_alt_151;

  assign c$case_alt_151 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd78) ? (c$app_arg_6[473 : 468]) : c$case_alt_152;

  assign c$case_alt_152 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd79) ? (c$app_arg_6[479 : 474]) : c$case_alt_153;

  assign c$case_alt_153 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd80) ? (c$app_arg_6[485 : 480]) : c$case_alt_154;

  assign c$case_alt_154 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd81) ? (c$app_arg_6[491 : 486]) : c$case_alt_155;

  assign c$case_alt_155 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd82) ? (c$app_arg_6[497 : 492]) : c$case_alt_156;

  assign c$case_alt_156 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd83) ? (c$app_arg_6[503 : 498]) : c$case_alt_157;

  assign c$case_alt_157 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd84) ? (c$app_arg_6[509 : 504]) : c$case_alt_158;

  assign c$case_alt_158 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd85) ? (c$app_arg_6[515 : 510]) : c$case_alt_159;

  assign c$case_alt_159 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd86) ? (c$app_arg_6[521 : 516]) : c$case_alt_160;

  assign c$case_alt_160 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd87) ? (c$app_arg_6[527 : 522]) : c$case_alt_161;

  assign c$case_alt_161 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd88) ? (c$app_arg_6[533 : 528]) : c$case_alt_162;

  assign c$case_alt_162 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd89) ? (c$app_arg_6[539 : 534]) : c$case_alt_163;

  assign c$case_alt_163 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd90) ? (c$app_arg_6[545 : 540]) : c$case_alt_164;

  assign c$case_alt_164 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd91) ? (c$app_arg_6[551 : 546]) : c$case_alt_165;

  assign c$case_alt_165 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd92) ? (c$app_arg_6[557 : 552]) : c$case_alt_166;

  assign c$case_alt_166 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd93) ? (c$app_arg_6[563 : 558]) : c$case_alt_167;

  assign c$case_alt_167 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd94) ? (c$app_arg_6[569 : 564]) : c$case_alt_168;

  assign c$case_alt_168 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd95) ? (c$app_arg_6[575 : 570]) : c$case_alt_169;

  assign c$case_alt_169 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd96) ? (c$app_arg_6[581 : 576]) : c$case_alt_170;

  assign c$case_alt_170 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd97) ? (c$app_arg_6[587 : 582]) : c$case_alt_171;

  assign c$case_alt_171 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd98) ? (c$app_arg_6[593 : 588]) : c$case_alt_172;

  assign c$case_alt_172 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd99) ? (c$app_arg_6[599 : 594]) : c$case_alt_173;

  assign c$case_alt_173 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd100) ? (c$app_arg_6[605 : 600]) : c$case_alt_174;

  assign c$case_alt_174 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd101) ? (c$app_arg_6[611 : 606]) : c$case_alt_175;

  assign c$case_alt_175 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd102) ? (c$app_arg_6[617 : 612]) : c$case_alt_176;

  assign c$case_alt_176 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd103) ? (c$app_arg_6[623 : 618]) : c$case_alt_177;

  assign c$case_alt_177 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd104) ? (c$app_arg_6[629 : 624]) : c$case_alt_178;

  assign c$case_alt_178 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd105) ? (c$app_arg_6[635 : 630]) : c$case_alt_179;

  assign c$case_alt_179 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd106) ? (c$app_arg_6[641 : 636]) : c$case_alt_180;

  assign c$case_alt_180 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd107) ? (c$app_arg_6[647 : 642]) : c$case_alt_181;

  assign c$case_alt_181 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd108) ? (c$app_arg_6[653 : 648]) : c$case_alt_182;

  assign c$case_alt_182 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd109) ? (c$app_arg_6[659 : 654]) : c$case_alt_183;

  assign c$case_alt_183 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd110) ? (c$app_arg_6[665 : 660]) : c$case_alt_184;

  assign c$case_alt_184 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd111) ? (c$app_arg_6[671 : 666]) : c$case_alt_185;

  assign c$case_alt_185 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd112) ? (c$app_arg_6[677 : 672]) : c$case_alt_186;

  assign c$case_alt_186 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd113) ? (c$app_arg_6[683 : 678]) : c$case_alt_187;

  assign c$case_alt_187 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd114) ? (c$app_arg_6[689 : 684]) : c$case_alt_188;

  assign c$case_alt_188 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd115) ? (c$app_arg_6[695 : 690]) : c$case_alt_189;

  assign c$case_alt_189 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd116) ? (c$app_arg_6[701 : 696]) : c$case_alt_190;

  assign c$case_alt_190 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd117) ? (c$app_arg_6[707 : 702]) : c$case_alt_191;

  assign c$case_alt_191 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd118) ? (c$app_arg_6[713 : 708]) : c$case_alt_192;

  assign c$case_alt_192 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd119) ? (c$app_arg_6[719 : 714]) : c$case_alt_193;

  assign c$case_alt_193 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd120) ? (c$app_arg_6[725 : 720]) : c$case_alt_194;

  assign c$case_alt_194 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd121) ? (c$app_arg_6[731 : 726]) : c$case_alt_195;

  assign c$case_alt_195 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd122) ? (c$app_arg_6[737 : 732]) : c$case_alt_196;

  assign c$case_alt_196 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd123) ? (c$app_arg_6[743 : 738]) : c$case_alt_197;

  assign c$case_alt_197 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd124) ? (c$app_arg_6[749 : 744]) : c$case_alt_198;

  assign c$case_alt_198 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd125) ? (c$app_arg_6[755 : 750]) : c$case_alt_199;

  assign c$case_alt_199 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd126) ? (c$app_arg_6[761 : 756]) : c$case_alt_200;

  assign c$case_alt_200 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd127) ? (c$app_arg_6[767 : 762]) : c$case_alt_201;

  assign c$case_alt_201 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd128) ? (c$app_arg_6[773 : 768]) : c$case_alt_202;

  assign c$case_alt_202 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd129) ? (c$app_arg_6[779 : 774]) : c$case_alt_203;

  assign c$case_alt_203 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd130) ? (c$app_arg_6[785 : 780]) : c$case_alt_204;

  assign c$case_alt_204 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd131) ? (c$app_arg_6[791 : 786]) : c$case_alt_205;

  assign c$case_alt_205 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd132) ? (c$app_arg_6[797 : 792]) : c$case_alt_206;

  assign c$case_alt_206 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd133) ? (c$app_arg_6[803 : 798]) : c$case_alt_207;

  assign c$case_alt_207 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd134) ? (c$app_arg_6[809 : 804]) : c$case_alt_208;

  assign c$case_alt_208 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd135) ? (c$app_arg_6[815 : 810]) : c$case_alt_209;

  assign c$case_alt_209 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd136) ? (c$app_arg_6[821 : 816]) : c$case_alt_210;

  assign c$case_alt_210 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd137) ? (c$app_arg_6[827 : 822]) : c$case_alt_211;

  assign c$case_alt_211 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd138) ? (c$app_arg_6[833 : 828]) : c$case_alt_212;

  assign c$case_alt_212 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd139) ? (c$app_arg_6[839 : 834]) : c$case_alt_213;

  assign c$case_alt_213 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd140) ? (c$app_arg_6[845 : 840]) : c$case_alt_214;

  assign c$case_alt_214 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd141) ? (c$app_arg_6[851 : 846]) : c$case_alt_215;

  assign c$case_alt_215 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd142) ? (c$app_arg_6[857 : 852]) : c$case_alt_216;

  assign c$case_alt_216 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd143) ? (c$app_arg_6[863 : 858]) : c$case_alt_217;

  assign c$case_alt_217 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd144) ? (c$app_arg_6[869 : 864]) : c$case_alt_218;

  assign c$case_alt_218 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd145) ? (c$app_arg_6[875 : 870]) : c$case_alt_219;

  assign c$case_alt_219 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd146) ? (c$app_arg_6[881 : 876]) : c$case_alt_220;

  assign c$case_alt_220 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd147) ? (c$app_arg_6[887 : 882]) : c$case_alt_221;

  assign c$case_alt_221 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd148) ? (c$app_arg_6[893 : 888]) : c$case_alt_222;

  assign c$case_alt_222 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd149) ? (c$app_arg_6[899 : 894]) : c$case_alt_223;

  assign c$case_alt_223 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd150) ? (c$app_arg_6[905 : 900]) : c$case_alt_224;

  assign c$case_alt_224 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd151) ? (c$app_arg_6[911 : 906]) : c$case_alt_225;

  assign c$case_alt_225 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd152) ? (c$app_arg_6[917 : 912]) : c$case_alt_226;

  assign c$case_alt_226 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd153) ? (c$app_arg_6[923 : 918]) : c$case_alt_227;

  assign c$case_alt_227 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd154) ? (c$app_arg_6[929 : 924]) : c$case_alt_228;

  assign c$case_alt_228 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd155) ? (c$app_arg_6[935 : 930]) : c$case_alt_229;

  assign c$case_alt_229 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd156) ? (c$app_arg_6[941 : 936]) : c$case_alt_230;

  assign c$case_alt_230 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd157) ? (c$app_arg_6[947 : 942]) : c$case_alt_231;

  assign c$case_alt_231 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd158) ? (c$app_arg_6[953 : 948]) : c$case_alt_232;

  assign c$case_alt_232 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd159) ? (c$app_arg_6[959 : 954]) : c$case_alt_233;

  assign c$case_alt_233 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd160) ? (c$app_arg_6[965 : 960]) : c$case_alt_234;

  assign c$case_alt_234 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd161) ? (c$app_arg_6[971 : 966]) : c$case_alt_235;

  assign c$case_alt_235 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd162) ? (c$app_arg_6[977 : 972]) : c$case_alt_236;

  assign c$case_alt_236 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd163) ? (c$app_arg_6[983 : 978]) : c$case_alt_237;

  assign c$case_alt_237 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd164) ? (c$app_arg_6[989 : 984]) : c$case_alt_238;

  assign c$case_alt_238 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd165) ? (c$app_arg_6[995 : 990]) : c$case_alt_239;

  assign c$case_alt_239 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd166) ? (c$app_arg_6[1001 : 996]) : c$case_alt_240;

  assign c$case_alt_240 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd167) ? (c$app_arg_6[1007 : 1002]) : c$case_alt_241;

  assign c$case_alt_241 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd168) ? (c$app_arg_6[1013 : 1008]) : c$case_alt_242;

  assign c$case_alt_242 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd169) ? (c$app_arg_6[1019 : 1014]) : c$case_alt_243;

  assign c$case_alt_243 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd170) ? (c$app_arg_6[1025 : 1020]) : c$case_alt_244;

  assign c$case_alt_244 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd171) ? (c$app_arg_6[1031 : 1026]) : c$case_alt_245;

  assign c$case_alt_245 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd172) ? (c$app_arg_6[1037 : 1032]) : c$case_alt_246;

  assign c$case_alt_246 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd173) ? (c$app_arg_6[1043 : 1038]) : c$case_alt_247;

  assign c$case_alt_247 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd174) ? (c$app_arg_6[1049 : 1044]) : c$case_alt_248;

  assign c$case_alt_248 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd175) ? (c$app_arg_6[1055 : 1050]) : c$case_alt_249;

  assign c$case_alt_249 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd176) ? (c$app_arg_6[1061 : 1056]) : c$case_alt_250;

  assign c$case_alt_250 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd177) ? (c$app_arg_6[1067 : 1062]) : c$case_alt_251;

  assign c$case_alt_251 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd178) ? (c$app_arg_6[1073 : 1068]) : c$case_alt_252;

  assign c$case_alt_252 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd179) ? (c$app_arg_6[1079 : 1074]) : c$case_alt_253;

  assign c$case_alt_253 = (($unsigned(c$cbdDiff6_arg0_app_arg_1[0+:8])) == 8'd180) ? (c$app_arg_6[1085 : 1080]) : ({6 {1'bx}});

  assign c$app_arg_6 = block;

  assign block = c$ds_app_arg[1607:8];

  assign c$cbdDiff6_arg0_app_arg_1 = $unsigned({{(64-8) {1'b0}},idx_0});

  assign idx_0 = c$ds_app_arg[1615:1608];

  Component_SamplePolyCBD512_i264o12_keccakF1600 Component_SamplePolyCBD512_i264o12_keccakF1600_c$keccakF1600_out
    ( .result (c$keccakF1600_out)
    , .roundIdx (roundIdx)
    , .x (state) );

  assign state = c$ds_app_arg[1602:3];

  assign roundIdx = c$ds_app_arg[1615:1611];

  assign DIGEST_TDATA_0 = result.Tuple2_3_sel0;

  assign DIGEST_TVALID = result.Tuple2_3_sel1;

  assign DIGEST_TDATA = DIGEST_TDATA_0;


endmodule

