# clash-hash OpenSTA Report Generation

source [file join [file dirname [info script]] sta_common.tcl]

# Configuration for path analysis
set sta_overall_paths 10
set sta_paths_per_group 5

# Get all input and output ports for path group analysis
set inputs {}
set outputs {}

foreach port [get_ports] {
    set port_name [get_property $port name]
    set port_direction [get_property $port direction]

    if {$port_direction == "input"} {
        lappend inputs [list $port_name]
    } elseif {$port_direction == "output"} {
        lappend outputs [list $port_name]
    }
}

puts "Found [llength $inputs] input ports and [llength $outputs] output ports"

# Generate overall timing report
set reports_dir $::env(STA_OUTPUT_DIR_FULL)/reports
set overall_rpt_file "${reports_dir}/timing/overall"
file mkdir [file dirname $overall_rpt_file]

puts "Generating overall timing report..."
if {[catch {
    # Generate overall timing report without specifying path group (covers all paths)
    set sta_report_out_filename "${overall_rpt_file}.rpt"
    set sta_csv_out_filename "${overall_rpt_file}.csv.rpt"

    puts "Reporting overall timing to $sta_report_out_filename and $sta_csv_out_filename"
    report_checks -group_path_count $sta_overall_paths > $sta_report_out_filename

    # Generate CSV version for overall timing
    if {[catch {find_timing_paths -group_path_count $sta_overall_paths} paths]} {
        puts "Warning: Could not find timing paths for overall report"
    } else {
        set sta_csv_out [open $sta_csv_out_filename "w"]
        puts $sta_csv_out "startpoint,endpoint,slack"

        foreach path $paths {
            if {[catch {
                set startpoint_name [get_property [get_property $path startpoint] full_name]
                set endpoint_name [get_property [get_property $path endpoint] full_name]
                set slack [get_property $path slack]
                puts $sta_csv_out [format "$startpoint_name,$endpoint_name,%.4f" $slack]
            } error]} {
                puts "Warning: Error processing path in overall report: $error"
            }
        }
        close $sta_csv_out
    }
} error]} {
    puts "Warning: Could not generate overall timing report: $error"
}

# Setup path groups and generate reports
set path_group_list [list]

puts "Setting up path groups..."
setup_path_groups $inputs $outputs path_group_list

puts "Found path groups: $path_group_list"

foreach path_group $path_group_list {
    puts "Generating report for path group: $path_group"
    set path_group_rpt_file "${reports_dir}/timing/$path_group"
    file mkdir [file dirname $path_group_rpt_file]

    if {[catch {
        timing_report $path_group $path_group_rpt_file $sta_paths_per_group
    } error]} {
        puts "Warning: Could not generate report for $path_group: $error"
    }
}

# Generate additional reports
puts "Generating area report..."
if {[catch {
    # Generate basic design report
    set area_file [open "${reports_dir}/area.rpt" w]
    puts $area_file "Design Statistics Report (Generated by clash-hash STA)"
    puts $area_file "======================================================="
    puts $area_file "Top Module: $top_module"
    puts $area_file "Input Ports: [llength [all_inputs]]"
    puts $area_file "Output Ports: [llength [all_outputs]]"
    puts $area_file "Total Ports: [expr [llength [all_inputs]] + [llength [all_outputs]]]"
    puts $area_file ""
    puts $area_file "Note: Detailed area analysis requires synthesis tool reports."
    puts $area_file "For complete area information, check synthesis output files."
    close $area_file
} error]} {
    puts "Warning: Could not generate area report: $error"
}

puts "Generating clock report..."
if {[catch {
    set clock_file [open "${reports_dir}/clocks.rpt" w]
    puts $clock_file "Clock Report (Generated by clash-hash STA)"
    puts $clock_file "=========================================="

    if {[catch {all_clocks} clocks]} {
        puts $clock_file "No clocks found in design"
    } else {
        if {[llength $clocks] > 0} {
            puts $clock_file "Found [llength $clocks] clock(s):"
            foreach clock $clocks {
                if {[catch {
                    set clock_name [get_property $clock name]
                    set clock_period [get_property $clock period]
                    puts $clock_file "  Clock: $clock_name, Period: $clock_period ns"
                } clock_error]} {
                    puts $clock_file "  Clock: $clock (details unavailable)"
                }
            }
        } else {
            puts $clock_file "No clocks found in design"
        }
    }
    close $clock_file
} error]} {
    puts "Warning: Could not generate clock report: $error"
}

# Generate summary metrics using OpenSTA built-in commands
puts "Generating summary metrics report..."
if {[catch {
    set summary_file "${reports_dir}/summary.rpt"

    # Check if this is a pure combinational design
    set flops_count [llength [all_registers -edge_triggered]]
    set is_combinational [expr {$flops_count == 0}]

    # Get metrics from OpenSTA
    report_wns -digits 3 > "${summary_file}.tmp.wns"
    report_tns -digits 3 > "${summary_file}.tmp.tns"
    report_worst_slack -max > "${summary_file}.tmp.slack"

    # Read and parse the values
    set wns_fd [open "${summary_file}.tmp.wns" r]
    set wns_line [string trim [read $wns_fd]]
    close $wns_fd

    set tns_fd [open "${summary_file}.tmp.tns" r]
    set tns_line [string trim [read $tns_fd]]
    close $tns_fd

    set slack_fd [open "${summary_file}.tmp.slack" r]
    set slack_line [string trim [read $slack_fd]]
    close $slack_fd

    # Clean up temp files
    file delete "${summary_file}.tmp.wns"
    file delete "${summary_file}.tmp.tns"
    file delete "${summary_file}.tmp.slack"

    # Extract numeric values (format: "wns max 0.000" -> "0.000")
    set has_timing [regexp {([0-9.]+)$} $wns_line -> wns_val]
    regexp {([0-9.]+)$} $tns_line -> tns_val
    regexp {([0-9.]+)$} $slack_line -> slack_val

    # Write formatted table
    set fd [open $summary_file w]

    if {$is_combinational} {
        puts $fd "Design Type:     Pure Combinational (No Registers)"
        puts $fd ""

        # Try to get combinational delay from in2out paths
        # Read the already-generated in2out.rpt file
        set in2out_rpt_file "${reports_dir}/timing/in2out.rpt"
        if {[file exists $in2out_rpt_file]} {
            if {[catch {
                # Read the in2out report file
                set report_fd [open $in2out_rpt_file r]
                set report_content [read $report_fd]
                close $report_fd

                # Extract data arrival time and required time from the report
                # Look for lines like: "           0.43   data arrival time"
                set comb_delay 0.0
                set required 10.0
                set slack_num 0.0

                # Split into lines and find the values
                # First occurrence of each is the actual value we want
                set found_arrival 0
                set found_required 0
                set found_slack 0

                foreach line [split $report_content "\n"] {
                    # Look for "data arrival time" line with a number (may have leading spaces)
                    if {!$found_arrival && [regexp {\s*([0-9.]+)\s+data arrival time\s*$} $line match val]} {
                        set comb_delay $val
                        set found_arrival 1
                    }
                    # Look for "data required time" line
                    if {!$found_required && [regexp {\s*([0-9.]+)\s+data required time\s*$} $line match val]} {
                        set required $val
                        set found_required 1
                    }
                    # Look for slack line
                    if {!$found_slack && [regexp {\s*([0-9.]+)\s+slack \(([A-Z]+)\)} $line match val status]} {
                        if {$status == "VIOLATED"} {
                            set slack_num [expr {-1.0 * $val}]
                        } else {
                            set slack_num $val
                        }
                        set found_slack 1
                    }
                }

                if {$found_arrival} {
                    puts $fd [format "Combinational Delay: %.3f ns" $comb_delay]
                    puts $fd [format "Required Time:       %.3f ns" $required]
                    puts $fd [format "Slack:               %.3f ns" $slack_num]
                    puts $fd ""

                    # Calculate max frequency
                    if {$comb_delay > 0} {
                        set max_freq [expr {1000.0 / $comb_delay}]
                        puts $fd [format "Max Frequency:       %.2f MHz (if used combinationally)" $max_freq]
                    }
                } else {
                    puts $fd "Could not extract timing values from in2out report"
                }
            } error]} {
                puts $fd "Error reading in2out report: $error"
                puts $fd "See timing/in2out.rpt for detailed timing information"
            }
        } else {
            puts $fd "No combinational paths found"
        }
    } else {
        puts $fd "Design Type:     Sequential (With Registers)"
        puts $fd ""

        if {$has_timing} {
            # Try to extract critical path timing from reg2reg report
            set reg2reg_rpt_file "${reports_dir}/timing/reg2reg.rpt"
            set critical_path_ns "N/A"

            if {[file exists $reg2reg_rpt_file]} {
                if {[catch {
                    set report_fd [open $reg2reg_rpt_file r]
                    set report_content [read $report_fd]
                    close $report_fd

                    # Look for the first "data arrival time" line
                    set found_arrival 0
                    foreach line [split $report_content "\n"] {
                        if {!$found_arrival && [regexp {\s*([0-9.]+)\s+data arrival time\s*$} $line match val]} {
                            set critical_path_ns $val
                            set found_arrival 1
                            break
                        }
                    }
                } error]} {
                    # Silently ignore errors
                }
            }

            puts $fd [format "Critical Path:   %s ns" $critical_path_ns]
            puts $fd [format "WNS (max):       %s ns" $wns_val]
            puts $fd [format "TNS (max):       %s ns" $tns_val]
            puts $fd [format "Worst Slack:     %s ns" $slack_val]
        } else {
            puts $fd "No timing paths found"
        }
    }

    close $fd
} error]} {
    puts "Warning: Could not generate summary metrics report: $error"
}

puts ""
puts "Static timing analysis completed!"
puts "Reports available in: $reports_dir"

exit
