/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module dut
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic [271:0] SEED_TDATA
    , input wire logic SEED_TVALID
    , input wire logic SEED_TLAST
    , input wire logic COEFF_TREADY

      // Outputs
    , output logic [47:0] COEFF_TDATA
    , output logic COEFF_TVALID
    , output logic COEFF_TLAST
    , output logic SEED_TREADY
    );
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  logic [135:0] c$ds1_app_arg = {4'b0000,132'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
  logic [1599:0] result_0;
  logic [1599:0] c$app_arg;
  logic [1599:0] result_1;
  logic [1599:0] c$app_arg_0;
  logic [1599:0] result_2;
  logic [1599:0] c$app_arg_1;
  logic [1599:0] result_3;
  logic [1599:0] c$app_arg_2;
  logic [1599:0] result_4;
  logic [1599:0] c$app_arg_3;
  logic [1599:0] result_5;
  logic [1599:0] c$app_arg_4;
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  logic [1599:0] c$keccakState_case_alt;
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  logic [1599:0] c$keccakState_case_alt_0;
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  logic [1599:0] c$keccakState_case_alt_1;
  dut_types::Tuple2_3 result_6;
  // src/Component/SampleNTT6O48.hs:121:1-9
  logic [271:0] inputMsg;
  // src/Component/SampleNTT6O48.hs:121:1-9
  logic msgValid;
  // src/Component/SampleNTT6O48.hs:121:1-9
  logic [4:0] counter;
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  logic coeffReady;
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  dut_types::AXI4Stream seedStream;
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  logic [6:0] phase = {2'b00,5'bxxxxx};
  dut_types::Tuple3_0 c$case_alt;
  dut_types::Tuple3_0 c$case_alt_0;
  dut_types::Tuple3_0 c$case_alt_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic msgValid_0;
  dut_types::Tuple3_0 result_7;
  dut_types::Tuple3_0 result_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  dut_types::Tuple2_4 ds3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] k;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] j;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] i;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] j_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] i_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] i_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_6;
  dut_types::Tuple3_0 result_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [6:0] nextPhase;
  // src/Component/SampleNTT6O48.hs:90:1-11
  dut_types::Tuple2_4 ds3_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] k_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] j_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] i_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] j_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] i_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] i_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] h_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] g_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_11;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_11;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_11;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_11;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] f_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_11;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_12;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_12;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_12;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_12;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] e_12;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_13;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_13;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_13;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_13;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] a_14;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] b_14;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] d_14;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c_14;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic c$$j_app_arg;
  logic [135:0] result_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  dut_types::array_of_9_logic_vector_136 ws;
  dut_types::array_of_8_logic_vector_136 result_11;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [11:0] c0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$c0_app_arg;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] chunk;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_1;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_2;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_3;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_4;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_5;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_6;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_7;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_8;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_9;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_10;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [95:0] c$chunk_case_alt_11;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic c$chunk_case_scrut;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [3:0] counter_0;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [1599:0] c$chunk_app_arg;
  // src/Component/SampleNTT6O48.hs:90:1-11
  logic [4:0] counter_1;
  // src/Component/SampleNTT6O48.hs:(129,1)-(131,17)
  logic [1599:0] keccakState = 1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
  dut_types::Tuple2_5 c$arg;
  dut_types::array_of_8_Tuple2_6 c$vec1;
  dut_types::array_of_8_logic_vector_136 c$vec2;
  dut_types::Tuple2_7 result;
  dut_types::AXI4Stream_0 COEFF;

  assign c$arg = {{SEED_TDATA
                  ,SEED_TVALID
                  ,SEED_TLAST}
                 ,COEFF_TREADY};

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : c$ds1_app_arg_register
    if ( RST) begin
      c$ds1_app_arg <= {4'b0000,132'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
    end else  if (EN)  begin
      c$ds1_app_arg <= c$case_alt.Tuple3_0_sel1;
    end
  end
  // register end

  // replaceBit start
  always_comb begin
    result_0 = c$app_arg;
    result_0[64'sd272] = (~ (c$app_arg[64'sd272]));
  end
  // replaceBit end

  assign c$app_arg = result_1;

  // replaceBit start
  always_comb begin
    result_1 = c$app_arg_0;
    result_1[64'sd273] = (~ (c$app_arg_0[64'sd273]));
  end
  // replaceBit end

  assign c$app_arg_0 = result_2;

  // replaceBit start
  always_comb begin
    result_2 = c$app_arg_1;
    result_2[64'sd274] = (~ (c$app_arg_1[64'sd274]));
  end
  // replaceBit end

  assign c$app_arg_1 = result_3;

  // replaceBit start
  always_comb begin
    result_3 = c$app_arg_2;
    result_3[64'sd275] = (~ (c$app_arg_2[64'sd275]));
  end
  // replaceBit end

  assign c$app_arg_2 = result_4;

  // replaceBit start
  always_comb begin
    result_4 = c$app_arg_3;
    result_4[64'sd276] = (~ (c$app_arg_3[64'sd276]));
  end
  // replaceBit end

  assign c$app_arg_3 = ({1328'b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,inputMsg});

  // replaceBit start
  always_comb begin
    result_5 = c$app_arg_4;
    result_5[64'sd1343] = (~ (c$app_arg_4[64'sd1343]));
  end
  // replaceBit end

  assign c$app_arg_4 = result_0;

  assign c$keccakState_case_alt = msgValid ? result_5 : keccakState;

  Component_SampleNTT6O48_i272o48l6_keccakF1600 Component_SampleNTT6O48_i272o48l6_keccakF1600_c$keccakState_case_alt_0
    ( .result (c$keccakState_case_alt_0)
    , .c$arg (counter)
    , .c$arg_0 (keccakState) );

  always_comb begin
    case(phase[6:5])
      2'b00 : c$keccakState_case_alt_1 = c$keccakState_case_alt;
      2'b01 : c$keccakState_case_alt_1 = c$keccakState_case_alt_0;
      default : c$keccakState_case_alt_1 = keccakState;
    endcase
  end

  assign result_6 = {c$case_alt[50:50]
                    ,c$case_alt[49:0]};

  assign inputMsg = seedStream.AXI4Stream_sel0;

  assign msgValid = seedStream.AXI4Stream_sel1;

  assign counter = phase[4:0];

  assign coeffReady = c$arg.Tuple2_5_sel1;

  assign seedStream = c$arg.Tuple2_5_sel0;

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : phase_register
    if ( RST) begin
      phase <= {2'b00,5'bxxxxx};
    end else  if (EN)  begin
      phase <= c$case_alt.Tuple3_0_sel0;
    end
  end
  // register end

  always_comb begin
    case(phase[6:5])
      2'b00 : c$case_alt = c$case_alt_1;
      2'b01 : c$case_alt = c$case_alt_0;
      default : c$case_alt = result_7;
    endcase
  end

  assign c$case_alt_0 = (counter_1 == 5'd23) ? {{2'b10,4'd0,1'bx}
                                               ,c$ds1_app_arg
                                               ,{1'b0
                                                ,{48'b000000000000000000000000000000000000000000000000
                                                 ,1'b0
                                                 ,1'b0}}} : {{2'b01,counter_1 + 5'd1}
                                                            ,c$ds1_app_arg
                                                            ,{1'b0
                                                             ,{48'b000000000000000000000000000000000000000000000000
                                                              ,1'b0
                                                              ,1'b0}}};

  assign c$case_alt_1 = msgValid_0 ? {{2'b01,5'd0}
                                     ,{4'b0000,132'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}
                                     ,{1'b0
                                      ,{48'b000000000000000000000000000000000000000000000000
                                       ,1'b0
                                       ,1'b0}}} : {{2'b00,5'bxxxxx}
                                                  ,c$ds1_app_arg
                                                  ,{1'b1
                                                   ,{48'b000000000000000000000000000000000000000000000000
                                                    ,1'b0
                                                    ,1'b0}}};

  assign msgValid_0 = seedStream.AXI4Stream_sel1;

  always_comb begin
    case(c$ds1_app_arg[135:132])
      4'b0000 : result_7 = result_9;
      4'b0001 : result_7 = result_9;
      4'b0010 : result_7 = result_9;
      4'b0011 : result_7 = result_9;
      default : result_7 = result_8;
    endcase
  end

  assign result_8 = coeffReady ? {phase
                                 ,ds3.Tuple2_4_sel1
                                 ,{1'b0,{ds3.Tuple2_4_sel0,1'b1,1'b0}}} : {phase
                                                                          ,c$ds1_app_arg
                                                                          ,{1'b0,{ds3.Tuple2_4_sel0,1'b1,1'b0}}};

  always_comb begin
    case(c$ds1_app_arg[135:132])
      4'b0100 : ds3 = {{({({d_6,c_6}),b_6}),a_6}
                      ,{4'b0000,132'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b0101 : ds3 = {{({({d_5,c_5}),b_5}),a_5}
                      ,{4'b0001,e_5,120'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b0110 : ds3 = {{({({d_4,c_4}),b_4}),a_4}
                      ,{4'b0010,e_4,f_4,108'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b0111 : ds3 = {{({({d_3,c_3}),b_3}),a_3}
                      ,{4'b0011,e_3,f_3,g_3,96'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b1000 : ds3 = {{({({d_2,c_2}),b_2}),a_2}
                      ,{4'b0100,e_2,f_2,g_2,h_2,84'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b1001 : ds3 = {{({({d_1,c_1}),b_1}),a_1}
                      ,{4'b0101,e_1,f_1,g_1,h_1,i_1,72'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b1010 : ds3 = {{({({d_0,c_0}),b_0}),a_0}
                      ,{4'b0110,e_0,f_0,g_0,h_0,i_0,j_0,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      default : ds3 = {{({({d,c}),b}),a}
                      ,{4'b0111,e,f,g,h,i,j,k,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
    endcase
  end

  assign k = c$ds1_app_arg[11:0];

  assign j = c$ds1_app_arg[23:12];

  assign i = c$ds1_app_arg[35:24];

  assign h = c$ds1_app_arg[47:36];

  assign g = c$ds1_app_arg[59:48];

  assign f = c$ds1_app_arg[71:60];

  assign e = c$ds1_app_arg[83:72];

  assign a = c$ds1_app_arg[131:120];

  assign b = c$ds1_app_arg[119:108];

  assign d = c$ds1_app_arg[95:84];

  assign c = c$ds1_app_arg[107:96];

  assign j_0 = c$ds1_app_arg[23:12];

  assign i_0 = c$ds1_app_arg[35:24];

  assign h_0 = c$ds1_app_arg[47:36];

  assign g_0 = c$ds1_app_arg[59:48];

  assign f_0 = c$ds1_app_arg[71:60];

  assign e_0 = c$ds1_app_arg[83:72];

  assign a_0 = c$ds1_app_arg[131:120];

  assign b_0 = c$ds1_app_arg[119:108];

  assign d_0 = c$ds1_app_arg[95:84];

  assign c_0 = c$ds1_app_arg[107:96];

  assign i_1 = c$ds1_app_arg[35:24];

  assign h_1 = c$ds1_app_arg[47:36];

  assign g_1 = c$ds1_app_arg[59:48];

  assign f_1 = c$ds1_app_arg[71:60];

  assign e_1 = c$ds1_app_arg[83:72];

  assign a_1 = c$ds1_app_arg[131:120];

  assign b_1 = c$ds1_app_arg[119:108];

  assign d_1 = c$ds1_app_arg[95:84];

  assign c_1 = c$ds1_app_arg[107:96];

  assign h_2 = c$ds1_app_arg[47:36];

  assign g_2 = c$ds1_app_arg[59:48];

  assign f_2 = c$ds1_app_arg[71:60];

  assign e_2 = c$ds1_app_arg[83:72];

  assign a_2 = c$ds1_app_arg[131:120];

  assign b_2 = c$ds1_app_arg[119:108];

  assign d_2 = c$ds1_app_arg[95:84];

  assign c_2 = c$ds1_app_arg[107:96];

  assign g_3 = c$ds1_app_arg[59:48];

  assign f_3 = c$ds1_app_arg[71:60];

  assign e_3 = c$ds1_app_arg[83:72];

  assign a_3 = c$ds1_app_arg[131:120];

  assign b_3 = c$ds1_app_arg[119:108];

  assign d_3 = c$ds1_app_arg[95:84];

  assign c_3 = c$ds1_app_arg[107:96];

  assign f_4 = c$ds1_app_arg[71:60];

  assign e_4 = c$ds1_app_arg[83:72];

  assign a_4 = c$ds1_app_arg[131:120];

  assign b_4 = c$ds1_app_arg[119:108];

  assign d_4 = c$ds1_app_arg[95:84];

  assign c_4 = c$ds1_app_arg[107:96];

  assign e_5 = c$ds1_app_arg[83:72];

  assign a_5 = c$ds1_app_arg[131:120];

  assign b_5 = c$ds1_app_arg[119:108];

  assign d_5 = c$ds1_app_arg[95:84];

  assign c_5 = c$ds1_app_arg[107:96];

  assign a_6 = c$ds1_app_arg[131:120];

  assign b_6 = c$ds1_app_arg[119:108];

  assign d_6 = c$ds1_app_arg[95:84];

  assign c_6 = c$ds1_app_arg[107:96];

  assign result_9 = (c$$j_app_arg & coeffReady) ? {nextPhase
                                                  ,ds3_0.Tuple2_4_sel1
                                                  ,{1'b0
                                                   ,{ds3_0.Tuple2_4_sel0,1'b1,1'b0}}} : {nextPhase
                                                                                        ,result_10
                                                                                        ,{1'b0
                                                                                         ,{48'b000000000000000000000000000000000000000000000000
                                                                                          ,1'b0
                                                                                          ,1'b0}}};

  assign nextPhase = c$chunk_case_scrut ? {2'b01,5'd0} : {2'b10,counter_0 + 4'd1,1'bx};

  always_comb begin
    case(result_10[135:132])
      4'b0100 : ds3_0 = {{({({d_14,c_14}),b_14}),a_14}
                        ,{4'b0000,132'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b0101 : ds3_0 = {{({({d_13,c_13}),b_13}),a_13}
                        ,{4'b0001,e_12,120'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b0110 : ds3_0 = {{({({d_12,c_12}),b_12}),a_12}
                        ,{4'b0010,e_11,f_10,108'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b0111 : ds3_0 = {{({({d_11,c_11}),b_11}),a_11}
                        ,{4'b0011,e_10,f_9,g_8,96'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b1000 : ds3_0 = {{({({d_10,c_10}),b_10}),a_10}
                        ,{4'b0100,e_9,f_8,g_7,h_6,84'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b1001 : ds3_0 = {{({({d_9,c_9}),b_9}),a_9}
                        ,{4'b0101,e_8,f_7,g_6,h_5,i_4,72'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b1010 : ds3_0 = {{({({d_8,c_8}),b_8}),a_8}
                        ,{4'b0110,e_7,f_6,g_5,h_4,i_3,j_2,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      4'b1011 : ds3_0 = {{({({d_7,c_7}),b_7}),a_7}
                        ,{4'b0111,e_6,f_5,g_4,h_3,i_2,j_1,k_0,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx}};
      default : ds3_0 = {184 {1'bx}};
    endcase
  end

  assign k_0 = result_10[11:0];

  assign j_1 = result_10[23:12];

  assign i_2 = result_10[35:24];

  assign h_3 = result_10[47:36];

  assign g_4 = result_10[59:48];

  assign f_5 = result_10[71:60];

  assign e_6 = result_10[83:72];

  assign a_7 = result_10[131:120];

  assign b_7 = result_10[119:108];

  assign d_7 = result_10[95:84];

  assign c_7 = result_10[107:96];

  assign j_2 = result_10[23:12];

  assign i_3 = result_10[35:24];

  assign h_4 = result_10[47:36];

  assign g_5 = result_10[59:48];

  assign f_6 = result_10[71:60];

  assign e_7 = result_10[83:72];

  assign a_8 = result_10[131:120];

  assign b_8 = result_10[119:108];

  assign d_8 = result_10[95:84];

  assign c_8 = result_10[107:96];

  assign i_4 = result_10[35:24];

  assign h_5 = result_10[47:36];

  assign g_6 = result_10[59:48];

  assign f_7 = result_10[71:60];

  assign e_8 = result_10[83:72];

  assign a_9 = result_10[131:120];

  assign b_9 = result_10[119:108];

  assign d_9 = result_10[95:84];

  assign c_9 = result_10[107:96];

  assign h_6 = result_10[47:36];

  assign g_7 = result_10[59:48];

  assign f_8 = result_10[71:60];

  assign e_9 = result_10[83:72];

  assign a_10 = result_10[131:120];

  assign b_10 = result_10[119:108];

  assign d_10 = result_10[95:84];

  assign c_10 = result_10[107:96];

  assign g_8 = result_10[59:48];

  assign f_9 = result_10[71:60];

  assign e_10 = result_10[83:72];

  assign a_11 = result_10[131:120];

  assign b_11 = result_10[119:108];

  assign d_11 = result_10[95:84];

  assign c_11 = result_10[107:96];

  assign f_10 = result_10[71:60];

  assign e_11 = result_10[83:72];

  assign a_12 = result_10[131:120];

  assign b_12 = result_10[119:108];

  assign d_12 = result_10[95:84];

  assign c_12 = result_10[107:96];

  assign e_12 = result_10[83:72];

  assign a_13 = result_10[131:120];

  assign b_13 = result_10[119:108];

  assign d_13 = result_10[95:84];

  assign c_13 = result_10[107:96];

  assign a_14 = result_10[131:120];

  assign b_14 = result_10[119:108];

  assign d_14 = result_10[95:84];

  assign c_14 = result_10[107:96];

  always_comb begin
    case(result_10[135:132])
      4'b0000 : c$$j_app_arg = 1'b0;
      4'b0001 : c$$j_app_arg = 1'b0;
      4'b0010 : c$$j_app_arg = 1'b0;
      4'b0011 : c$$j_app_arg = 1'b0;
      default : c$$j_app_arg = 1'b1;
    endcase
  end

  assign result_10 = ws[$high(ws)];

  assign ws = dut_types::array_of_9_logic_vector_136_cons(c$ds1_app_arg, result_11);

  assign c$vec1 = '{0: {c0 < 12'b110100000001,c0}
                   ,1: {c1 < 12'b110100000001,c1}
                   ,2: {c2 < 12'b110100000001,c2}
                   ,3: {c3 < 12'b110100000001,c3}
                   ,4: {c4 < 12'b110100000001,c4}
                   ,5: {c5 < 12'b110100000001,c5}
                   ,6: {c6 < 12'b110100000001,c6}
                   ,7: {c7 < 12'b110100000001,c7}};

  assign c$vec2 = (ws[0 : $high(ws) - 1]);

  // zipWith begin
  genvar n;
  generate
  for (n = 0; n < $size(result_11); n = n + 1) begin : zipWith
    dut_types::Tuple2_6 zipWith_in1;
    assign zipWith_in1 = c$vec1[n];
    logic [135:0] zipWith_in2;
    assign zipWith_in2 = c$vec2[n];
    logic [135:0] zipWith_out;
    logic [135:0] c$case_alt_7;
    logic [135:0] c$case_alt_6;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_2;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_3;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_2;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c4_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_4;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_3;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_2;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c4_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c5_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_5;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_4;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_3;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c4_2;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c5_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c6_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_6;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_5;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_4;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c4_3;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c5_2;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c6_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c7_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_7;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_6;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_5;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c4_4;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c5_3;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c6_2;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c7_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c8;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_8;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_7;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_6;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c4_5;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c5_4;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c6_3;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c7_2;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c8_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c9;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c1_9;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c2_8;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c3_7;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c4_6;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c5_5;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c6_4;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c7_3;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c8_1;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c9_0;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] c10;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic isValid;
    // src/Component/SampleNTT6O48.hs:90:1-11
    logic [11:0] candidate;
    assign zipWith_out = c$case_alt_6;

    always_comb begin
      case(zipWith_in2[135:132])
        4'b0000 : c$case_alt_7 = {4'b0001,candidate,120'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b0001 : c$case_alt_7 = {4'b0010,c1_0,candidate,108'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b0010 : c$case_alt_7 = {4'b0011,c1_1,c2_0,candidate,96'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b0011 : c$case_alt_7 = {4'b0100,c1_2,c2_1,c3_0,candidate,84'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b0100 : c$case_alt_7 = {4'b0101,c1_3,c2_2,c3_1,c4_0,candidate,72'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b0101 : c$case_alt_7 = {4'b0110,c1_4,c2_3,c3_2,c4_1,c5_0,candidate,60'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b0110 : c$case_alt_7 = {4'b0111,c1_5,c2_4,c3_3,c4_2,c5_1,c6_0,candidate,48'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b0111 : c$case_alt_7 = {4'b1000,c1_6,c2_5,c3_4,c4_3,c5_2,c6_1,c7_0,candidate,36'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b1000 : c$case_alt_7 = {4'b1001,c1_7,c2_6,c3_5,c4_4,c5_3,c6_2,c7_1,c8,candidate,24'bxxxxxxxxxxxxxxxxxxxxxxxx};
        4'b1001 : c$case_alt_7 = {4'b1010,c1_8,c2_7,c3_6,c4_5,c5_4,c6_3,c7_2,c8_0,c9,candidate,12'bxxxxxxxxxxxx};
        4'b1010 : c$case_alt_7 = {4'b1011,c1_9,c2_8,c3_7,c4_6,c5_5,c6_4,c7_3,c8_1,c9_0,c10,candidate};
        default : c$case_alt_7 = zipWith_in2;
      endcase
    end

    assign c$case_alt_6 = isValid ? c$case_alt_7 : zipWith_in2;

    assign c1_0 = zipWith_in2[131:120];

    assign c1_1 = zipWith_in2[131:120];

    assign c2_0 = zipWith_in2[119:108];

    assign c1_2 = zipWith_in2[131:120];

    assign c2_1 = zipWith_in2[119:108];

    assign c3_0 = zipWith_in2[107:96];

    assign c1_3 = zipWith_in2[131:120];

    assign c2_2 = zipWith_in2[119:108];

    assign c3_1 = zipWith_in2[107:96];

    assign c4_0 = zipWith_in2[95:84];

    assign c1_4 = zipWith_in2[131:120];

    assign c2_3 = zipWith_in2[119:108];

    assign c3_2 = zipWith_in2[107:96];

    assign c4_1 = zipWith_in2[95:84];

    assign c5_0 = zipWith_in2[83:72];

    assign c1_5 = zipWith_in2[131:120];

    assign c2_4 = zipWith_in2[119:108];

    assign c3_3 = zipWith_in2[107:96];

    assign c4_2 = zipWith_in2[95:84];

    assign c5_1 = zipWith_in2[83:72];

    assign c6_0 = zipWith_in2[71:60];

    assign c1_6 = zipWith_in2[131:120];

    assign c2_5 = zipWith_in2[119:108];

    assign c3_4 = zipWith_in2[107:96];

    assign c4_3 = zipWith_in2[95:84];

    assign c5_2 = zipWith_in2[83:72];

    assign c6_1 = zipWith_in2[71:60];

    assign c7_0 = zipWith_in2[59:48];

    assign c1_7 = zipWith_in2[131:120];

    assign c2_6 = zipWith_in2[119:108];

    assign c3_5 = zipWith_in2[107:96];

    assign c4_4 = zipWith_in2[95:84];

    assign c5_3 = zipWith_in2[83:72];

    assign c6_2 = zipWith_in2[71:60];

    assign c7_1 = zipWith_in2[59:48];

    assign c8 = zipWith_in2[47:36];

    assign c1_8 = zipWith_in2[131:120];

    assign c2_7 = zipWith_in2[119:108];

    assign c3_6 = zipWith_in2[107:96];

    assign c4_5 = zipWith_in2[95:84];

    assign c5_4 = zipWith_in2[83:72];

    assign c6_3 = zipWith_in2[71:60];

    assign c7_2 = zipWith_in2[59:48];

    assign c8_0 = zipWith_in2[47:36];

    assign c9 = zipWith_in2[35:24];

    assign c1_9 = zipWith_in2[131:120];

    assign c2_8 = zipWith_in2[119:108];

    assign c3_7 = zipWith_in2[107:96];

    assign c4_6 = zipWith_in2[95:84];

    assign c5_5 = zipWith_in2[83:72];

    assign c6_4 = zipWith_in2[71:60];

    assign c7_3 = zipWith_in2[59:48];

    assign c8_1 = zipWith_in2[47:36];

    assign c9_0 = zipWith_in2[35:24];

    assign c10 = zipWith_in2[23:12];

    assign isValid = zipWith_in1.Tuple2_6_sel0;

    assign candidate = zipWith_in1.Tuple2_6_sel1;


    assign result_11[n] = zipWith_out;
  end
  endgenerate
  // zipWith end

  assign c7 = c$c0_app_arg[95 : 84];

  assign c6 = c$c0_app_arg[83 : 72];

  assign c5 = c$c0_app_arg[71 : 60];

  assign c4 = c$c0_app_arg[59 : 48];

  assign c3 = c$c0_app_arg[47 : 36];

  assign c2 = c$c0_app_arg[35 : 24];

  assign c1 = c$c0_app_arg[23 : 12];

  assign c0 = c$c0_app_arg[11 : 0];

  assign c$c0_app_arg = chunk;

  assign chunk = (counter_0 == 4'd0) ? (c$chunk_app_arg[95 : 0]) : c$chunk_case_alt;

  assign c$chunk_case_alt = (counter_0 == 4'd1) ? (c$chunk_app_arg[191 : 96]) : c$chunk_case_alt_0;

  assign c$chunk_case_alt_0 = (counter_0 == 4'd2) ? (c$chunk_app_arg[287 : 192]) : c$chunk_case_alt_1;

  assign c$chunk_case_alt_1 = (counter_0 == 4'd3) ? (c$chunk_app_arg[383 : 288]) : c$chunk_case_alt_2;

  assign c$chunk_case_alt_2 = (counter_0 == 4'd4) ? (c$chunk_app_arg[479 : 384]) : c$chunk_case_alt_3;

  assign c$chunk_case_alt_3 = (counter_0 == 4'd5) ? (c$chunk_app_arg[575 : 480]) : c$chunk_case_alt_4;

  assign c$chunk_case_alt_4 = (counter_0 == 4'd6) ? (c$chunk_app_arg[671 : 576]) : c$chunk_case_alt_5;

  assign c$chunk_case_alt_5 = (counter_0 == 4'd7) ? (c$chunk_app_arg[767 : 672]) : c$chunk_case_alt_6;

  assign c$chunk_case_alt_6 = (counter_0 == 4'd8) ? (c$chunk_app_arg[863 : 768]) : c$chunk_case_alt_7;

  assign c$chunk_case_alt_7 = (counter_0 == 4'd9) ? (c$chunk_app_arg[959 : 864]) : c$chunk_case_alt_8;

  assign c$chunk_case_alt_8 = (counter_0 == 4'd10) ? (c$chunk_app_arg[1055 : 960]) : c$chunk_case_alt_9;

  assign c$chunk_case_alt_9 = (counter_0 == 4'd11) ? (c$chunk_app_arg[1151 : 1056]) : c$chunk_case_alt_10;

  assign c$chunk_case_alt_10 = (counter_0 == 4'd12) ? (c$chunk_app_arg[1247 : 1152]) : c$chunk_case_alt_11;

  assign c$chunk_case_alt_11 = c$chunk_case_scrut ? (c$chunk_app_arg[1343 : 1248]) : ({96 {1'bx}});

  assign c$chunk_case_scrut = counter_0 == 4'd13;

  assign counter_0 = phase[4:1];

  assign c$chunk_app_arg = keccakState;

  assign counter_1 = phase[4:0];

  // register begin
  always_ff @(posedge CLK or  posedge  RST) begin : keccakState_register
    if ( RST) begin
      keccakState <= 1600'b0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000;
    end else  if (EN)  begin
      keccakState <= c$keccakState_case_alt_1;
    end
  end
  // register end

  assign result = {result_6.Tuple2_3_sel1
                  ,result_6.Tuple2_3_sel0};

  assign COEFF = result.Tuple2_7_sel0;

  assign SEED_TREADY = result.Tuple2_7_sel1;

  assign COEFF_TDATA = COEFF.AXI4Stream_0_sel0;

  assign COEFF_TVALID = COEFF.AXI4Stream_0_sel1;

  assign COEFF_TLAST = COEFF.AXI4Stream_0_sel2;


endmodule

