name: clash-hash
version: 0.1
license: MIT
author: Chen-Mou Cheng <chenmou.cheng@gmail.com>
maintainer: Chen-Mou Cheng <chenmou.cheng@gmail.com>

default-extensions:
  - NoImplicitPrelude
  - DataKinds
  - NoStarIsType
  - AllowAmbiguousTypes
  - DeriveAnyClass
  - DerivingStrategies
  - TemplateHaskell
  - QuasiQuotes
  - MagicHash

ghc-options:
  - -Wall
  - -Wcompat
  - -haddock
  - -fplugin GHC.TypeLits.Extra.Solver
  - -fplugin GHC.TypeLits.Normalise
  - -fplugin GHC.TypeLits.KnownNat.Solver
  - -fconstraint-solver-iterations=0
  - -fexpose-all-unfoldings
  - -fno-worker-wrapper
  - -fno-unbox-small-strict-fields
  - -fno-unbox-strict-fields

dependencies:
  - base

flags:
  executables:
    description: Build executables (clash, clashi, trace) - disable for faster tests
    manual: true
    default: false

library:
  language: GHC2021
  source-dirs: src
  dependencies:
    - Cabal
    - modular-arithmetic
    - template-haskell
    - clash-prelude >= 1.8.1 && < 1.10
    - ghc-typelits-natnormalise
    - ghc-typelits-extra
    - ghc-typelits-knownnat
    - clash-multicycle-moore
    - bytestring
    - crypton
    - memory
    - constraints
    - vector

executables:
  clash:
    main: bin/Clash.hs
    language: GHC2021
    when:
      - condition: flag(executables)
        then:
          buildable: true
        else:
          buildable: false
    dependencies:
      - clash-ghc
      - clash-hash
      - ghc-typelits-extra
      - ghc-typelits-natnormalise
      - ghc-typelits-knownnat
  clashi:
    main: bin/Clashi.hs
    language: GHC2021
    when:
      - condition: flag(executables)
        then:
          buildable: true
        else:
          buildable: false
    dependencies:
      - clash-ghc
      - clash-hash
      - ghc-typelits-extra
      - ghc-typelits-natnormalise
      - ghc-typelits-knownnat
  trace:
    main: Trace.hs
    source-dirs:
      - app
      - tests
    language: GHC2021
    ghc-options:
      - -threaded
    when:
      - condition: flag(executables)
        then:
          buildable: true
        else:
          buildable: false
    other-modules:
      - Driver
    dependencies:
      - text
      - directory
      - clash-prelude
      - clash-hash
      - ghc-typelits-extra
      - ghc-typelits-natnormalise
      - ghc-typelits-knownnat

tests:
  clash-hash-test:
    main: Main.hs
    source-dirs:
      - tests
    language: GHC2021
    ghc-options:
      - -threaded
    dependencies:
      - clash-prelude
      - clash-hash
      - ghc-typelits-extra
      - ghc-typelits-natnormalise
      - ghc-typelits-knownnat
      - tasty >= 1.2 && < 1.5
      - tasty-hspec
      - hspec
      - QuickCheck
      - bytestring
      - crypton
      - memory
      - vector
      - process
      - filepath
      - aeson
