/* AUTOMATICALLY GENERATED SYSTEMVERILOG-2005 SOURCE CODE.
** GENERATED BY CLASH 1.8.2. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module dut
    ( // Inputs
      input wire logic CLK  // clock
    , input wire logic RST  // reset
    , input wire logic EN  // enable
    , input wire logic SHAKE_TREADY
    , input wire logic [65:0] MSG_TDATA
    , input wire logic MSG_TVALID

      // Outputs
    , output logic [63:0] SHAKE_TDATA
    , output logic SHAKE_TVALID
    , output logic SHAKE_TLAST
    , output logic MSG_TREADY
    );
  dut_types::Tuple2_4 result_0;
  dut_types::Tuple2_5 result_1;
  dut_types::Tuple2_4 MSG;
  dut_types::Tuple3_0 result_fun_arg;
  dut_types::Tuple2_4 result;
  dut_types::AXI4Stream SHAKE;

  assign MSG = {MSG_TDATA,MSG_TVALID};

  assign result_fun_arg = {MSG.Tuple2_4_sel0
                          ,SHAKE_TREADY
                          ,MSG.Tuple2_4_sel1};

  Component_SHAKE128_i64o64_spongeFSM i64o64Core_Component_SHAKE128_i64o64_spongeFSM_result_0
    ( .result (result_0)
    , .c$ds_bindCsr (CLK)
    , .c$ds_bindCsr_0 (RST)
    , .c$ds_bindCsr_1 (EN)
    , .eta1 (result_fun_arg) );

  assign result_1 = {result_0.Tuple2_4_sel1
                    ,result_0.Tuple2_4_sel0};

  assign result = {result_1.Tuple2_5_sel1
                  ,result_1.Tuple2_5_sel0};

  assign SHAKE = result.Tuple2_4_sel0;

  assign MSG_TREADY = result.Tuple2_4_sel1;

  assign SHAKE_TDATA = SHAKE.AXI4Stream_sel0;

  assign SHAKE_TVALID = SHAKE.AXI4Stream_sel1;

  assign SHAKE_TLAST = SHAKE.AXI4Stream_sel2;


endmodule

